using System.Text;
using TSpec.Internal.Specification;
using static TSpec.Internal.Document.DocumentText;

namespace TSpec.Internal.Document;

internal enum DocumentSegmentStyle
{
    /// Markdown the layout assembled itself, emitted as it stands.
    Raw,

    /// Specification text, which Render quotes inline or fences depending on how it came out.
    Code,

    /// A section heading at <see cref="DocumentSegment.Level"/>.
    Heading,
}

internal sealed record DocumentSegment(
    string Text,
    DocumentSegmentStyle Style = DocumentSegmentStyle.Raw,
    int Level = 0)
{
    internal static DocumentSegment Ruler => new("\n---\n");
}

internal class Render(DocumentSegment[] segments)
{
    private StringBuilder? _text;
    public override string ToString() => (_text ??= Build()).ToString();

    private StringBuilder Build()
    {
        StringBuilder text = new();
        foreach (var segment in segments)
            text.Append(Rendered(segment));
        return text;
    }

    private static string Rendered(DocumentSegment segment) => segment.Style switch
    {
        DocumentSegmentStyle.Code => Block(segment.Text),
        DocumentSegmentStyle.Heading
            => $"\n{new string('#', segment.Level)} {segment.Text}\n",
        _ => segment.Text,
    };
}

internal class Represent(
        SpecificationSubject subject,
        string specAssemblyName,
        string buildId,
        IEnumerable<SpecificationEntry> entries)
{
    private Document? _document;

    internal Document Document => _document ??= Document.Of(subject, specAssemblyName, buildId, entries);
}

internal class Layout(Document document)
{
    private DocumentSegment[]? _segments;

    internal DocumentSegment[] Segments => _segments ??= LayOut();

    private DocumentSegment[] LayOut()
    {
        List<DocumentSegment> segments = [];
        AddTitle();
        AddContent();
        return [.. segments];

        void AddTitle()
        {
            AddText($"# {document.Subject.Name.AsTitle()}\n\n");
            AddText($"<!-- Version {document.Subject.Version}+{document.BuildId}, ");
            AddText($"generated by TSpec from {document.SpecAssemblyName}. Do not edit by hand. -->\n");
        }

        void AddContent()
        {
            AddCode(HeadingStatement.Body(document.Declared, document.Whole, stated: null));
            if (document.Areas.Count > 0)
                AppendRequirements();
        }

        void AppendRequirements()
        {
            Add(DocumentSegment.Ruler);
            foreach (var area in Order(document.Areas))
                AddNode(area, document.Declared);
        }

        void AddNode(DocumentNode node, Declared stated)
        {
            if (node.Heading is not null)
            {
                Add(new DocumentSegment(
                    node.Heading, DocumentSegmentStyle.Heading, node.Level));
                AddCode(HeadingStatement.Body(
                    node.Declaration.Except(stated), node.Shared, StatedWord(node.Heading)));
            }

            if (node is BranchNode branch)
                AddLeaves(branch);
            else
                foreach (var section in Order(node.Children))
                    AddNode(section, stated.And(node.Declaration));
        }

        void AddLeaves(BranchNode branch)
        {
            AddText("\n");
            foreach (var requirement in InReadingOrder(branch.Requirements))
                AddText(Leaf(requirement));
        }

        void AddText(string text) => Add(new DocumentSegment(text));

        // Nothing to say means nothing is written, so an empty statement is no segment at all.
        void AddCode(string text)
        {
            if (text.Length > 0)
                Add(new DocumentSegment(text, DocumentSegmentStyle.Code));
        }

        void Add(DocumentSegment segment) => segments.Add(segment);
    }

    /// <summary>
    /// The requirements of a branch as they read best: least arranged first, then shortest, so a
    /// reader meets preconditions gradually. Ties fall back to names, which are stable.
    /// </summary>
    private static IEnumerable<Requirement> InReadingOrder(IReadOnlyList<Requirement> requirements)
        => requirements
            .OrderBy(requirement => requirement.Arrangement)
            .ThenBy(requirement => Fit(
                Compose(requirement.Clauses, requirement.Entry.Because), DocumentWidth).Length)
            .ThenBy(requirement => requirement.Entry.Requirement, StringComparer.Ordinal)
            .ThenBy(requirement => requirement.Signature, StringComparer.Ordinal);

    /// <summary>
    /// Sections in the order they read: whatever heads nothing first, so its content is not
    /// swallowed by the heading before it, then simplest first, then by name.
    /// </summary>
    private static DocumentNode[] Order(IEnumerable<DocumentNode> nodes)
        => [..nodes.OrderBy(node => node.HasKey)
            .ThenBy(node => node.ComplexityNumber)
            .ThenBy(node => node.Key, StringComparer.Ordinal)];

    private static string Leaf(Requirement requirement)
    {
        var name = requirement.Entry.Requirement.AsHeading();
        var label = Without(StatedWord(name), name);
        var text = Compose(requirement.Clauses, requirement.Entry.Because)
            .Without(StepFamily.Then.Keyword());
        var claim = Fit(text, ClaimWidth);
        if (claim.Contains('\n'))
            return $"- **{label}**\n{Indent($"```\n{Fit(text, FenceWidth)}\n```")}\n";

        var beside = $"- **{label}** — `{claim}`";
        return beside.Length <= DocumentWidth
            ? $"{beside}\n"
            : $"- **{label}**\\\n{Indent($"`{claim}`")}\n";
    }
}

/// <summary>
/// Renders a specification document from test-specification. 
/// Line endings normalized to LF for platform independence.
/// Text normalized and organized to make equivalent specs byte-identical on every machine, allowing for automated diff-detection.
/// </summary>
internal class DocumentRenderer
{
    internal static string Render(
        SpecificationSubject subject, string specAssemblyName, string buildId,
        IEnumerable<SpecificationEntry> entries)
    {
        Represent represent = new(subject, specAssemblyName, buildId, entries);
        Layout layout = new(represent.Document);
        Render render = new(layout.Segments);
        return render.ToString();
    }
}