using System.Text;
using TSpec.Internal.Specification;

namespace TSpec.Internal.Document;

/// <summary>
/// Renders the specification document. Each entry's steps are rendered here rather than arriving as
/// finished text, so the document can lay them out its own way; what comes back has platform-native
/// line endings and is normalized to LF, since a Windows run would otherwise commit a file that
/// differs from a Linux one on every line. That plus full sorting makes the document byte-identical
/// on every machine, which is what lets its diff be reviewed.
/// </summary>
internal static class DocumentRenderer
{
    internal static string Render(
        SpecificationSubject subject, string specAssemblyName, string buildId,
        IEnumerable<SpecificationEntry> entries)
    {
        // Version and build id are provenance: they answer "which build produced this" for a diff
        // or a pipeline, never a question a reader of requirements has. Kept in the generated-file
        // comment, they stay in the file — and in its diff — without occupying the page.
        var text = new StringBuilder()
            .Append($"# {subject.Name.AsTitle()}\n\n")
            .Append($"<!-- Version {subject.Version}+{buildId}, ")
            .Append($"generated by TSpec from {specAssemblyName}. Do not edit by hand. -->\n");

        var requirements = Distinct(entries).ToArray();
        var declared = Declaration(requirements);
        var whole = SharedOpening(requirements);
        text.Append(HeadingBlock(declared.Text, whole, stated: null));

        foreach (var subjectNode in Subjects(requirements, whole.Count))
        {
            var subjectHeading = subjectNode.Key.AsHeading();
            text.Append($"\n## {subjectHeading}\n")
                .Append(HeadingBlock(
                    subjectNode.Declaration.Except(declared).Text,
                    subjectNode.Shared,
                    StatedWord(subjectHeading)));

            foreach (var branch in subjectNode.Branches)
            {
                if (branch.Key.Length > 0)
                {
                    var branchHeading = branch.Key.AsHeading();
                    text.Append($"\n### {branchHeading}\n")
                        .Append(HeadingBlock(null, branch.Shared, StatedWord(branchHeading)));
                }
                // A blank line opens the list, so no renderer has to decide whether a bullet may
                // interrupt the line above it. It costs no height: a margin is there either way.
                text.Append('\n');
                foreach (var requirement in branch.Requirements)
                    text.Append(Leaf(requirement));
            }
        }
        return text.ToString();
    }

    /// <summary>
    /// The subjects, simplest first. A node's <c>ComplexityNumber</c> is the arrangement stated at
    /// its own heading plus that of everything under it, so a reader meets preconditions gradually
    /// rather than all at once — and ties fall back to the name, which is stable.
    /// </summary>
    /// <remarks>
    /// Assertions are not counted, and that is what makes summing upward safe: adding a requirement
    /// to an existing branch changes no number anywhere in the tree, so no section moves. Only
    /// arrangement appearing or disappearing can reorder the document, which is a structural change
    /// worth seeing in the diff. Counting size instead would reshuffle whole subjects because one
    /// line was added, spending the very thing the document is reviewed for.
    /// </remarks>
    private static IEnumerable<SubjectNode> Subjects(Requirement[] requirements, int hoisted)
        => requirements
            .Select(requirement => requirement.Without(hoisted))
            .GroupBy(requirement => requirement.Entry.Subject)
            .Select(ToSubject)
            .OrderBy(subject => subject.ComplexityNumber)
            .ThenBy(subject => subject.Key, StringComparer.Ordinal);

    private static SubjectNode ToSubject(IGrouping<string, Requirement> group)
    {
        var ofSubject = group.ToArray();
        var shared = SharedOpening(ofSubject);
        return new(group.Key, shared, Declaration(ofSubject), [.. ofSubject
            .Select(requirement => requirement.Without(shared.Count))
            .GroupBy(requirement => requirement.Entry.Branch)
            .Select(ToBranch)
            .OrderBy(branch => branch.ComplexityNumber)
            .ThenBy(branch => branch.Key, StringComparer.Ordinal)]);
    }

    private static BranchNode ToBranch(IGrouping<string, Requirement> group)
    {
        var ofBranch = group.ToArray();
        // Without a branch heading there is nothing for a shared opening to be stated under.
        var shared = group.Key.Length > 0 ? SharedOpening(ofBranch) : [];
        return new(group.Key, shared, [.. ofBranch
            .Select(requirement => requirement.Without(shared.Count))
            .OrderBy(requirement => Arrangement(requirement.Clauses))
            .ThenBy(requirement => Render(requirement.Clauses, requirement.Entry.Because).Length)
            .ThenBy(requirement => requirement.Entry.Requirement, StringComparer.Ordinal)
            .ThenBy(requirement => requirement.Specification, StringComparer.Ordinal)]);
    }

    /// How much a heading's own clauses arrange, which is every phase but the claim itself.
    private static int Arrangement(IReadOnlyList<SpecificationClause> clauses)
        => clauses.Count(clause => clause.Phase != StepPhase.Assert);

    /// <summary>
    /// What a heading declares about the code it describes. Each label is carried separately, and
    /// null where the requirements below disagree and the statement belongs further down instead —
    /// a subject can hold for a whole document while every section returns something different.
    /// </summary>
    /// <remarks>
    /// Stated rather than phrased, because no one phrasing survives every spec: <c>Spec&lt;int&gt;</c>
    /// over a static calculation would read as nonsense in a sentence and reads plainly as a label.
    /// This is the document's own apparatus, like the title and the provenance comment — never a
    /// step, or it would appear in every per-test specification too. It stays out of
    /// <c>ComplexityNumber</c> for the same reason, and would cancel anyway.
    /// </remarks>
    private readonly record struct Declared(string? Subject, string? ReturnType)
    {
        internal Declared Except(Declared stated)
            => new(stated.Subject is null ? Subject : null,
                stated.ReturnType is null ? ReturnType : null);

        /// <summary>
        /// Two labels read as a pair, so where both are stated their values are set in a column.
        /// Alone, a label has nothing to line up with and is written plainly.
        /// </summary>
        internal string? Text => (Subject, ReturnType) switch
        {
            (null, null) => null,
            (not null, null) => $"{SubjectLabel} {Subject}",
            (null, not null) => $"{ReturnLabel} {ReturnType}",
            _ => $"{SubjectLabel} {Subject}\n"
                + $"{ReturnLabel.PadRight(SubjectLabel.Length)} {ReturnType}",
        };
    }

    private static Declared Declaration(Requirement[] requirements)
    {
        var first = requirements.FirstOrDefault()?.Entry;
        if (first?.SubjectUnderTest is null)
            return default;

        return new(
            requirements.All(r => r.Entry.SubjectUnderTest == first.SubjectUnderTest)
                ? first.SubjectUnderTest : null,
            requirements.All(r => r.Entry.ReturnType == first.ReturnType)
                ? first.ReturnType : null);
    }

    private const string SubjectLabel = "Subject under test:";
    private const string ReturnLabel = "Return type:";

    /// The specification under a heading: what it declares, then the clauses hoisted to it. Nothing
    /// to say means nothing is written at all, so a heading never opens an empty block.
    private static string HeadingBlock(
        string? declaration, IReadOnlyList<SpecificationClause> shared, string? stated)
    {
        string?[] parts = [declaration, shared.Count > 0 ? Render(shared, because: null) : null];
        // A blank line between them, because they are not the same kind of statement: what a spec
        // declares about the code is the document's own apparatus, and the clauses are specification.
        var body = string.Join("\n\n", parts.Where(part => !string.IsNullOrEmpty(part)));
        return body.Length == 0 ? string.Empty : Block(Without(stated, body));
    }

    /// <summary>
    /// A requirement as an item of a list. It gets no heading of its own: a heading here would be a
    /// fourth level, which renders at body size and so cannot be told from the third — and writing
    /// one takes two elements whose four margins are most of the document's height. Items of a tight
    /// list have no margins between them, and being a different kind of thing from the headings above
    /// them is what lets those headings read as a hierarchy at all.
    /// </summary>
    private static string Leaf(Requirement requirement)
    {
        var name = requirement.Entry.Requirement.AsHeading();
        // An item's place in the list is what says "then", so neither its label nor its claim says
        // it. Only the opening word goes: what follows keeps its own, which is what orders it.
        var label = Without(StatedWord(name), name);
        var claim = Without(
            StepFamily.Then.Keyword(), Render(requirement.Clauses, requirement.Entry.Because));
        return claim.Contains('\n')
            ? $"- **{label}**\n{Indent($"```\n{claim}\n```")}\n"
            : $"- **{label}** — `{claim}`\n";
    }

    /// <summary>
    /// The clauses every requirement here opens with — stated once under the heading instead of
    /// repeated in each block. Whole clauses only, never a fragment of one, and no minimum number of
    /// requirements: a lone one still belongs under the heading that names its context.
    /// </summary>
    /// <remarks>
    /// Assertions are excluded on principle, and it is that exclusion rather than any counting rule
    /// that keeps a block from being hollowed out: they are the claim each requirement exists to
    /// make, so two requirements agreeing on one is a coincidence to leave visible, not repetition
    /// to factor out. Arrangement and action are context, and context is what a heading is for.
    /// A leading "and ..." can never be left behind, because lead words are assigned while
    /// rendering — whatever clause a block now opens with is given its family's word.
    /// </remarks>
    private static IReadOnlyList<SpecificationClause> SharedOpening(Requirement[] requirements)
    {
        if (requirements.Length == 0)
            return [];

        var first = requirements[0].Clauses;
        // Hoisting must never empty a block, so the shortest requirement always keeps one clause.
        var limit = requirements.Min(requirement => requirement.Clauses.Count) - 1;
        var shared = 0;
        while (shared < limit
            && first[shared].Phase != StepPhase.Assert
            && requirements.All(requirement => requirement.Clauses[shared].Matches(first[shared])))
            shared++;

        return [.. first.Take(shared)];
    }

    /// Rendered up front because identity is the rendered text: a theory reports once per case, and
    /// cases differing only in generated values describe one and the same requirement.
    private static IEnumerable<Requirement> Distinct(IEnumerable<SpecificationEntry> entries)
        => entries
            .Select(entry => new Requirement(
                entry, SpecificationClause.Split(entry.Steps), Render(entry)))
            .DistinctBy(requirement => (
                requirement.Entry.Subject,
                requirement.Entry.Branch,
                requirement.Entry.Requirement,
                requirement.Specification));

    private static string Render(SpecificationEntry entry)
        => Render(SpecificationClause.Split(entry.Steps), entry.Because);

    private static string Render(IReadOnlyList<SpecificationClause> clauses, string? because)
        => SpecificationRenderer
            .Render(clauses.SelectMany(clause => clause.Steps), because, new TextBuilder())
            .NormalizeLineEndings();

    /// <summary>
    /// Specification text placed under a heading. One line goes inline, because a fence is an element
    /// of its own and pays a margin above and below for text that needs neither; several lines keep
    /// the fence, which is then what tells a reader there are several. Only the code is monospaced
    /// either way — the prose around it is the document's, not the specification's.
    /// </summary>
    /// <remarks>
    /// No blank line before it: a heading and an HTML comment are both leaf blocks that end at their
    /// own line, so what follows opens a block of its own either way and the blank line would render
    /// as nothing at all.
    /// </remarks>
    private static string Block(string specification)
        => specification.Contains('\n')
            ? $"```\n{specification}\n```\n"
            : $"`{specification}`\n";

    /// A block inside a list item is indented to the item's own text, or it would end the list.
    private static string Indent(string block)
        => string.Join("\n", block.Split('\n').Select(line => $"  {line}"));

    /// <summary>
    /// The lead word a heading states, which is then the one word the specification beneath it does
    /// not repeat: a heading reading "When add room" is not followed by "When ...".
    /// </summary>
    /// <remarks>
    /// Only a block's opening word is ever dropped, and only when something above it says that same
    /// word — a "Having" under a "Given" states something the heading did not, and further down the
    /// lead words are the structure of the statements they open.
    /// </remarks>
    private static string? StatedWord(string heading)
        => StepFamilies.Keywords.FirstOrDefault(
            word => heading.StartsWith($"{word} ", StringComparison.Ordinal));

    private static string Without(string? stated, string specification)
        => stated is not null && specification.StartsWith($"{stated} ", StringComparison.Ordinal)
            ? specification[(stated.Length + 1)..]
            : specification;

    /// One requirement with its specification broken into clauses, as hoisting consumes them.
    /// The rendered text rides along as its identity, and as the last word on ordering when two
    /// requirements share a name — a theory whose cases describe themselves differently.
    private sealed record Requirement(
        SpecificationEntry Entry, IReadOnlyList<SpecificationClause> Clauses, string Specification)
    {
        internal Requirement Without(int hoisted)
            => hoisted == 0 ? this : this with { Clauses = [.. Clauses.Skip(hoisted)] };
    }

    /// A subject and its branches, each already stripped of what is stated above it.
    private sealed record SubjectNode(
        string Key, IReadOnlyList<SpecificationClause> Shared, Declared Declaration, BranchNode[] Branches)
    {
        internal int ComplexityNumber
            => Arrangement(Shared) + Branches.Sum(branch => branch.ComplexityNumber);
    }

    /// A branch and its requirements. A subject with no branches has one of these with an empty key.
    private sealed record BranchNode(
        string Key, IReadOnlyList<SpecificationClause> Shared, Requirement[] Requirements)
    {
        internal int ComplexityNumber
            => Arrangement(Shared) + Requirements.Sum(requirement => Arrangement(requirement.Clauses));
    }
}
