using System.Text;
using TSpec.Internal.Specification;
using Xunit.Internal;

namespace TSpec.Internal.Document;

/// <summary>
/// Renders a specification document from test-specification. 
/// Line endings normalized to LF for platform independence.
/// Normalized and organized to make equivalent specs byte-identical
/// on every machine, allowing for automated diff-detection.
/// </summary>
internal class DocumentRenderer
{
    internal static string Render(
        SpecificationSubject subject, string specAssemblyName, string buildId,
        IEnumerable<SpecificationEntry> entries)
    {
        DocumentRenderer renderer = new(entries);
        renderer.AppendTitle(subject, specAssemblyName, buildId);
        renderer.AppendContent();
        return renderer.ToString();
    }

    private readonly Requirement[] _requirements;
    private readonly Declared _declared;
    private readonly IReadOnlyList<SpecificationClause> _whole;
    private readonly StringBuilder _text = new();

    private DocumentRenderer(IEnumerable<SpecificationEntry> entries)
    {
        _requirements = [.. MapToRequirements(entries)];
        _declared = Declaration(_requirements, returns: false);
        _whole = SharedClauses(_requirements, acts: false);
    }

    public override string ToString() => _text.ToString();

    private StringBuilder Append(string? text) => _text.Append(text);

    private void AppendTitle(SpecificationSubject subject, string specAssemblyName, string buildId)
        => Append($"# {subject.Name.AsTitle()}\n\n")
            .Append($"<!-- Version {subject.Version}+{buildId}, ")
            .Append($"generated by TSpec from {specAssemblyName}. Do not edit by hand. -->\n");

    private void AppendContent()
    {
        Append(HeadingBlock(_declared, _whole, stated: null));
        if (_requirements.Length > 0)
            AppendRequirements();
    }

    private void AppendRequirements()
    {
        Append("\n---\n");
        Areas(_requirements, _whole).ForEach(RenderArea);

        void RenderArea(AreaNode area)
        {
            if (area.Key.Length > 0)
                Append(Heading(1, area.Key.AsHeading(), area.Declaration.Except(_declared), area.Shared));

            var grouped = area.Groups.Length > 1;
            area.Groups.ForEach(RenderGroup);

            void RenderGroup(GroupNode group)
            {
                if (grouped)
                    Append(Heading(2, group.Key.AsTitle(),
                        group.Declaration.Except(_declared).Except(area.Declaration), group.Shared));
                int subjectLevel = grouped ? 3 : 2;
                group.Subjects.ForEach(RenderSubject);

                void RenderSubject(SubjectNode subjectNode)
                {
                    Append(Heading(subjectLevel, subjectNode.Key.AsHeading(),
                                    subjectNode.Declaration.Except(_declared).Except(area.Declaration)
                                        .Except(group.Declaration),
                                    subjectNode.Shared));
                    subjectNode.Branches.ForEach(RenderBranch);

                    void RenderBranch(BranchNode branch)
                    {
                        if (branch.Key.Length > 0)
                            Append(Heading(subjectLevel + 1, branch.Key.AsHeading(), default, branch.Shared));
                        Append("\n");
                        branch.Requirements.ForEach(r => Append(Leaf(r)));
                    }
                }
            }
        }
    }

    private static string Heading(int level, string heading, Declared declared, IReadOnlyList<SpecificationClause> shared)
        => $"\n{new string('#', level)} {heading}\n{HeadingBlock(declared, shared, StatedWord(heading))}";

    private static AreaNode[] Areas(
        Requirement[] requirements, IReadOnlyList<SpecificationClause> hoisted)
    {
        var rootLength = GetCommonRootLength(requirements);
        return Order(requirements
            .Select(requirement => requirement.Without(hoisted))
            .GroupBy(requirement => Area(requirement.Entry.Namespace, rootLength))
            .Select(area => ToArea(area, rootLength)));
    }

    private static int GetCommonRootLength(Requirement[] requirements)
    {
        var paths = requirements.Select(requirement => Segments(requirement.Entry.Namespace)).ToArray();
        if (paths.Length == 0)
            return 0;

        var first = paths[0];
        var max = first.Length;
        foreach (var path in paths)
            max = GetCommonPrefixLength(first, path, max);
        return max;
    }

    private static int GetCommonPrefixLength(string[] first, string[] second, int max)
    {
        var common = 0;
        while (common < max && common < second.Length && second[common] == first[common])
            common++;
        return common;
    }

    private static string Area(string? @namespace, int root)
    {
        var segments = Segments(@namespace);
        return segments.Length > root ? segments[root] : string.Empty;
    }

    private static string Group(string? @namespace, int groupIndex)
        => string.Join('.', Segments(@namespace).Skip(groupIndex));

    private static string[] Segments(string? @namespace)
        => @namespace?.Split('.', StringSplitOptions.RemoveEmptyEntries) ?? [];

    private static AreaNode ToArea(IGrouping<string, Requirement> area, int areaIndex)
    {
        var ofArea = area.ToArray();
        var shared = area.Key.Length > 0 ? SharedClauses(ofArea, acts: false) : [];
        var declared = area.Key.Length > 0 ? Declaration(ofArea, returns: false) : default;
        var groups = ofArea
            .Select(requirement => requirement.Without(shared))
            .GroupBy(requirement => Group(requirement.Entry.Namespace, areaIndex + 1))
            .ToArray();
        return new(area.Key, shared, declared, 
            Order(groups.Select(group => ToGroup(group, heads: groups.Length > 1))));
    }

    private static GroupNode ToGroup(IGrouping<string, Requirement> group, bool heads)
    {
        var ofGroup = group.ToArray();
        var shared = heads ? SharedClauses(ofGroup, acts: false) : [];
        var declared = heads ? Declaration(ofGroup, returns: false) : default;
        return new(group.Key, shared, declared, 
            Order(ofGroup
            .Select(requirement => requirement.Without(shared))
            .GroupBy(requirement => requirement.Entry.Subject)
            .Select(ToSubject)));
    }

    private static TNode[] Order<TNode>(IEnumerable<TNode> nodes)
        where TNode : DocumentNode
        => [..nodes.OrderBy(node => node.Key.Length > 0)
            .ThenBy(node => node.ComplexityNumber)
            .ThenBy(node => node.Key, StringComparer.Ordinal)];

    private static SubjectNode ToSubject(IGrouping<string, Requirement> group)
    {
        var ofSubject = group.ToArray();
        var shared = SharedClauses(ofSubject);
        return new(group.Key, shared, Declaration(ofSubject), 
            Order(ofSubject
            .Select(requirement => requirement.Without(shared))
            .GroupBy(requirement => requirement.Entry.Branch)
            .Select(ToBranch)));
    }

    private static BranchNode ToBranch(IGrouping<string, Requirement> group)
    {
        var ofBranch = group.ToArray();
        var shared = group.Key.Length > 0 ? SharedClauses(ofBranch) : [];
        return new(group.Key, shared, [.. ofBranch
            .Select(requirement => requirement.Without(shared))
            .OrderBy(requirement => Arrangement(requirement.Clauses))
            .ThenBy(requirement => Render(
                Compose(requirement.Clauses, requirement.Entry.Because), DocumentWidth).Length)
            .ThenBy(requirement => requirement.Entry.Requirement, StringComparer.Ordinal)
            .ThenBy(requirement => requirement.Specification, StringComparer.Ordinal)]);
    }

    private static int Arrangement(IReadOnlyList<SpecificationClause> clauses)
        => clauses.Count(clause => clause.Phase != StepPhase.Assert);

    private readonly record struct Declared(string? Subject, string? ReturnType)
    {
        internal Declared Except(Declared stated)
            => new(stated.Subject is null ? Subject : null,
                stated.ReturnType is null ? ReturnType : null);

        internal string? Text => (Subject, ReturnType) switch
        {
            (null, null) => null,
            (not null, null) => $"{SubjectLabel} {Subject}",
            (null, not null) => ReturnLine,
            _ => $"{SubjectLabel} {Subject}\n{ReturnLine}",
        };

        internal string? ReturnLine => ReturnType is null ? null : $"{ReturnLabel} {ReturnType}";
    }

    private static Declared Declaration(Requirement[] requirements, bool returns = true)
    {
        var first = requirements.FirstOrDefault()?.Entry;
        if (first?.SubjectUnderTest is null)
            return default;

        return new(
            requirements.All(r => r.Entry.SubjectUnderTest == first.SubjectUnderTest)
                ? first.SubjectUnderTest : null,
            returns && requirements.All(r => r.Entry.ReturnType == first.ReturnType)
                ? first.ReturnType : null);
    }

    private const string SubjectLabel = "Subject under test:";
    private const string ReturnLabel = "Return type:";

    private static string HeadingBlock(
        Declared declared, IReadOnlyList<SpecificationClause> shared, string? stated)
    {
        var above = declared with { ReturnType = null };
        var joins = declared.ReturnType is not null
            && shared.Any(clause => clause.Family == StepFamily.When)
            && Joins(above, shared, declared.ReturnType, stated);
        var trails = !joins && declared.ReturnType is not null && shared.Count > 0;
        var says = joins || trails ? above : declared;
        var clauses = shared.Count == 0
            ? null
            : Clauses(says, shared, joins ? declared.ReturnType : null, stated);
        string?[] parts = [says.Text, clauses, trails ? declared.ReturnLine : null];
        var body = string.Join("\n", parts.Where(part => !string.IsNullOrEmpty(part)));
        return body.Length == 0 ? string.Empty : Block(body);
    }

    private static bool Joins(
        Declared says, IReadOnlyList<SpecificationClause> shared, string returns, string? stated)
        => Lines(Clauses(says, shared, returns, stated)) == Lines(Clauses(says, shared, null, stated));

    private static string Clauses(
        Declared says, IReadOnlyList<SpecificationClause> shared, string? returns, string? stated)
        => Render(
            Compose(shared, because: null, returns).Without(says.Text is null ? stated : null),
            DocumentWidth);

    private static int Lines(string text) => text.Count(character => character == '\n');

    private static string Leaf(Requirement requirement)
    {
        var name = requirement.Entry.Requirement.AsHeading();
        var label = Without(StatedWord(name), name);
        var text = Compose(requirement.Clauses, requirement.Entry.Because)
            .Without(StepFamily.Then.Keyword());
        var claim = Render(text, ClaimWidth);
        if (claim.Contains('\n'))
            return $"- **{label}**\n{Indent($"```\n{Render(text, FenceWidth)}\n```")}\n";

        var beside = $"- **{label}** — `{claim}`";
        return beside.Length <= DocumentWidth
            ? $"{beside}\n"
            : $"- **{label}**\\\n{Indent($"`{claim}`")}\n";
    }

    private static List<SpecificationClause> SharedClauses(
        Requirement[] requirements, bool acts = true)
    {
        if (requirements.Length == 0)
            return [];

        var limit = requirements.Min(requirement => requirement.Clauses.Count) - 1;
        List<SpecificationClause> shared = [];
        foreach (var clause in requirements[0].Clauses)
        {
            if (shared.Count == limit)
                break;
            if (!acts && clause.Family == StepFamily.When)
                continue;
            var taken = shared.Count(hoisted => hoisted.Matches(clause));
            if (clause.Phase != StepPhase.Assert
                && requirements.All(requirement => requirement.Clauses.Count(clause.Matches) > taken))
                shared.Add(clause);
        }
        return shared;
    }

    private static IEnumerable<Requirement> MapToRequirements(IEnumerable<SpecificationEntry> entries)
        => entries
            .Select(entry => new Requirement(
                entry, SpecificationClause.Split(entry.Steps), Render(entry)))
            .DistinctBy(requirement => (
                requirement.Entry.Namespace,
                requirement.Entry.Subject,
                requirement.Entry.Branch,
                requirement.Entry.Requirement,
                requirement.Specification));

    private static string Render(SpecificationEntry entry)
        => Render(Compose(SpecificationClause.Split(entry.Steps), entry.Because), DocumentWidth);

    private static ComposedText Compose(
        IReadOnlyList<SpecificationClause> clauses, string? because, string? returns = null)
        => SpecificationRenderer.Compose(Steps(clauses, returns), because);

    private static string Render(ComposedText text, int maxLineLength)
        => text.Render(maxLineLength, ContinuationIndentation, Tolerance).NormalizeLineEndings();

    private static IEnumerable<SpecificationStep> Steps(
        IReadOnlyList<SpecificationClause> clauses, string? returns)
        => clauses.SelectMany(clause => returns is not null && clause.Family == StepFamily.When
            ? [.. clause.Steps, new SpecificationStep(StepLayout.Word)
                {
                    Body = $"returns {returns}",
                    Binder = ", ",
                }]
            : clause.Steps);

    private static string Block(string specification)
        => specification.Contains('\n')
            ? $"```\n{specification}\n```\n"
            : $"`{specification}`\n";

    private const int DocumentWidth = 90;

    private const int Tolerance = 10;

    private const int ItemIndentation = 2;

    private const int ContinuationIndentation = 2;

    private const int FenceWidth = DocumentWidth - ItemIndentation;

    private const int ClaimWidth = FenceWidth - 2;

    private static string Indent(string block)
        => string.Join("\n",
            block.Split('\n').Select(line => $"{new string(' ', ItemIndentation)}{line}"));

    private static string? StatedWord(string heading)
        => StepFamilies.Keywords.FirstOrDefault(
            word => heading.StartsWith($"{word} ", StringComparison.Ordinal));

    private static string Without(string? stated, string specification)
        => stated is not null && specification.StartsWith($"{stated} ", StringComparison.Ordinal)
            ? specification[(stated.Length + 1)..]
            : specification;

    private sealed record Requirement(
        SpecificationEntry Entry, IReadOnlyList<SpecificationClause> Clauses, string Specification)
    {
        internal Requirement Without(IReadOnlyList<SpecificationClause> hoisted)
        {
            if (hoisted.Count == 0)
                return this;

            List<SpecificationClause> remaining = [.. Clauses];
            foreach (var clause in hoisted)
                remaining.Remove(remaining.FirstOrDefault(clause.Matches)!);
            return this with { Clauses = remaining };
        }
    }

    private sealed record AreaNode(
        string Key, IReadOnlyList<SpecificationClause> Shared, Declared Declaration, GroupNode[] Groups)
        : DocumentGrouping<GroupNode>(Key, Shared, Groups);

    private sealed record GroupNode(
        string Key, IReadOnlyList<SpecificationClause> Shared, Declared Declaration, SubjectNode[] Subjects)
        : DocumentGrouping<SubjectNode>(Key, Shared, Subjects);

    private sealed record SubjectNode(
        string Key, IReadOnlyList<SpecificationClause> Shared, Declared Declaration, BranchNode[] Branches)
        : DocumentGrouping<BranchNode>(Key, Shared, Branches);

    private sealed record BranchNode(
        string Key, IReadOnlyList<SpecificationClause> Shared, Requirement[] Requirements) : DocumentNode(Key, Shared)
    {
        internal override int ComplexityNumber
            => Arrangement(Shared) + Requirements.Sum(requirement => Arrangement(requirement.Clauses));
    }

    private abstract record DocumentGrouping<TChild>(
        string Key, IReadOnlyList<SpecificationClause> Shared, TChild[] Children) : DocumentNode(Key, Shared)
        where TChild : DocumentNode
    {
        internal override int ComplexityNumber 
            => Arrangement(Shared) + Children.Sum(branch => branch.ComplexityNumber);
    }

    private abstract record DocumentNode(string Key, IReadOnlyList<SpecificationClause> Shared)
    {
        internal abstract int ComplexityNumber { get; }
    }
}