namespace TSpec.Internal.Document.RenderPipeline;

internal sealed record CommentSegment(string Text) : DocumentSegment
{
    /// What every generated file says of itself: the version it describes, and what it came from.
    internal static CommentSegment Generated(string version, string from)
        => new($"Version {version}, generated by TSpec from {from}. Do not edit by hand.");

    internal override string Render() => $"\n<!-- {Text} -->\n";
}
