using System.Text;
using TSpec.Internal.Specification;

namespace TSpec.Internal.Document.RenderPipeline;

/// <summary>
/// Renders a specification document from test-specification. 
/// Line endings normalized to LF for platform independence.
/// Text normalized and organized to make equivalent specs byte-identical on every machine, allowing for automated diff-detection.
/// </summary>
internal static class DocumentRenderer
{
    internal static string Render(
        SpecificationSubject subject, string specAssemblyName, string buildId,
        IEnumerable<SpecificationEntry> entries)
        => Document.Of(subject, specAssemblyName, buildId, entries).Layout().Render();

    private static DocumentSegment[] Layout(this Document _document)
    {
        List<DocumentSegment> _segments = [];
        Add(new TitleSegment(_document.Subject.Name.AsTitle()));
        Add(new CommentSegment(
            $"Version {_document.Subject.Version}+{_document.BuildId}, "
            + $"generated by TSpec from {_document.SpecAssemblyName}. Do not edit by hand."));
        Add(new CodeSegment(
            _document.SubjectUnderTest, _document.ReturnType, _document.Whole, Stated: null));
        if (_document.Areas.Count > 0)
            AddRequirements();
        return [.. _segments];

        void Add(DocumentSegment segment) => _segments.Add(segment);

        void AddRequirements()
        {
            Add(new RulerSegment());
            foreach (var area in Order(_document.Areas))
                AddNode(area, _document.SubjectUnderTest, _document.ReturnType);
        }

        // Each label is silent below the heading that already said it, and the two travel apart.
        void AddNode(DocumentNode node, string? statedSubject, string? statedReturnType)
        {
            if (node.Heading is not null)
            {
                Add(new HeadingSegment(node.Heading, node.Level));
                Add(new CodeSegment(
                    statedSubject is null ? node.SubjectUnderTest : null,
                    statedReturnType is null ? node.ReturnType : null,
                    node.Shared,
                    StatedWord(node.Heading)));
            }

            if (node is BranchNode branch)
                AddLeaves(branch);
            else
                foreach (var section in Order(node.Children))
                    AddNode(section,
                        statedSubject ?? node.SubjectUnderTest,
                        statedReturnType ?? node.ReturnType);
        }

        void AddLeaves(BranchNode branch)
        {
            Add(new NewLineSegment());
            foreach (var requirement in InReadingOrder(branch.Requirements))
                Add(new ListItemSegment(requirement.Name, requirement.Claim));
        }
    }

    private static IEnumerable<Requirement> InReadingOrder(IReadOnlyList<Requirement> requirements)
        => requirements
            .OrderBy(requirement => requirement.ArrangementCount)
            .ThenBy(requirement => requirement.Size)
            .ThenBy(requirement => requirement.Entry.Requirement, StringComparer.Ordinal)
            .ThenBy(requirement => requirement.Signature, StringComparer.Ordinal);

    private static DocumentNode[] Order(IEnumerable<DocumentNode> nodes)
        => [..nodes.OrderBy(node => node.HasKey)
            .ThenBy(node => node.ComplexityNumber)
            .ThenBy(node => node.Key, StringComparer.Ordinal)];

    internal static string? StatedWord(string heading)
        => StepFamilies.Keywords.FirstOrDefault(
            word => heading.StartsWith($"{word} ", StringComparison.Ordinal));

    private static string Render(this DocumentSegment[] segments)
    {
        StringBuilder text = new();
        foreach (var segment in segments)
            text.Append(segment.Render());
        return text.ToString();
    }
}