using System.Text;
using TSpec.Internal.Specification;

namespace TSpec.Internal.Document.RenderPipeline;

/// <summary>
/// Renders a specification document from test-specification. 
/// Line endings normalized to LF for platform independence.
/// Text normalized and organized to make equivalent specs byte-identical on every machine, allowing for automated diff-detection.
/// </summary>
internal static class DocumentRenderer
{
    internal static string Render(
        SpecificationSubject subject, string specAssemblyName, string? sourceId,
        IEnumerable<SpecificationEntry> entries)
        => Document.Of(subject, specAssemblyName, sourceId, entries).Layout().Render();

    private static DocumentSegment[] Layout(this Document _document)
    {
        List<DocumentSegment> _segments = [];
        Add(new TitleSegment(_document.Subject.Name.AsTitle()));
        Add(new CommentSegment(
            $"Version {_document.Subject.Version}{Identified(_document.SourceId)}, "
            + $"generated by TSpec from {_document.SpecAssemblyName}. Do not edit by hand."));
        Add(new CodeSegment(
            _document.SubjectUnderTest, _document.ReturnType, _document.Whole, Stated: null));
        if (_document.Areas.Count > 0)
            AddRequirements();
        return [.. _segments];

        void Add(DocumentSegment segment) => _segments.Add(segment);

        void AddRequirements()
        {
            Add(new RulerSegment());
            foreach (var area in Order(_document.Areas))
                AddNode(area, _document.SubjectUnderTest, _document.ReturnType);
        }

        void AddNode(DocumentNode node, string? statedSubject, string? statedReturnType)
        {
            if (node.Heading is not null)
                AddHeading(node, node.Heading, statedSubject, statedReturnType);
            if (node.Requirements.Count > 0)
                AddLeaves(node.Requirements);
            foreach (var section in Order(node.Children))
                AddNode(section,
                    statedSubject ?? node.SubjectUnderTest,
                    statedReturnType ?? node.ReturnType);
        }

        void AddHeading(DocumentNode node, string heading, string? statedSubject, string? statedReturnType)
        {
            Add(new HeadingSegment(heading, node.Level));
            Add(new CodeSegment(
                statedSubject is null ? node.SubjectUnderTest : null,
                statedReturnType is null ? node.ReturnType : null,
                node.Shared,
                StatedWord(heading)));
        }

        void AddLeaves(IReadOnlyList<Requirement> requirements)
        {
            Add(new NewLineSegment());
            foreach (var requirement in InReadingOrder(requirements))
                Add(new ListItemSegment(requirement.Name, requirement.Claim, requirement.Rows));
        }
    }

    private static IEnumerable<Requirement> InReadingOrder(IReadOnlyList<Requirement> requirements)
        => requirements
            .OrderBy(requirement => requirement.ArrangementCount)
            .ThenBy(requirement => requirement.Size)
            .ThenBy(requirement => requirement.Entry.Requirement, StringComparer.Ordinal)
            .ThenBy(requirement => requirement.Signature, StringComparer.Ordinal);

    private static DocumentNode[] Order(IEnumerable<DocumentNode> nodes)
        => [..nodes.OrderBy(node => node.HasKey)
            .ThenBy(node => node.ComplexityNumber)
            .ThenBy(node => node.Key, StringComparer.Ordinal)];

    /// <summary>
    /// The subject's version says which release the document describes; the id says which source
    /// that release was built from. A subject compiled without debug information has no source to
    /// name, and the version stands alone rather than trailing an empty suffix.
    /// </summary>
    private static string Identified(string? sourceId)
        => sourceId is null ? string.Empty : $"+{sourceId}";

    internal static string? StatedWord(string heading)
        => StepFamilies.Keywords.FirstOrDefault(
            word => heading.StartsWith($"{word} ", StringComparison.Ordinal));

    private static string Render(this DocumentSegment[] segments)
    {
        StringBuilder text = new();
        foreach (var segment in segments)
            text.Append(segment.Render());
        return Squeezed(text.ToString());
    }

    /// <summary>
    /// One blank line at most. Segments cannot see each other, so a table that closes its item with
    /// a blank line and a heading that opens with one would together leave a gap the document
    /// leaves nowhere else.
    /// </summary>
    private static string Squeezed(string text)
        => text.Contains("\n\n\n", StringComparison.Ordinal)
            ? Squeezed(text.Replace("\n\n\n", "\n\n", StringComparison.Ordinal))
            : text;
}