using TSpec.Internal.Specification;
using static TSpec.Internal.Document.RenderPipeline.DocumentText;
using static TSpec.Internal.Document.RenderPipeline.DocumentStyle;

namespace TSpec.Internal.Document.RenderPipeline;

internal class Layout(Document document)
{
    private DocumentSegment[]? _segments;

    internal DocumentSegment[] Segments => _segments ??= LayOut();

    private DocumentSegment[] LayOut()
    {
        List<DocumentSegment> segments = [];
        AddTitle();
        AddContent();
        return [.. segments];

        void AddTitle()
        {
            AddText($"# {document.Subject.Name.AsTitle()}\n\n");
            AddText($"<!-- Version {document.Subject.Version}+{document.BuildId}, ");
            AddText($"generated by TSpec from {document.SpecAssemblyName}. Do not edit by hand. -->\n");
        }

        void AddContent()
        {
            AddCode(HeadingStatement.Body(document.Declared, document.Whole, stated: null));
            if (document.Areas.Count > 0)
                AppendRequirements();
        }

        void AppendRequirements()
        {
            Add(DocumentSegment.Ruler);
            foreach (var area in Order(document.Areas))
                AddNode(area, document.Declared);
        }

        void AddNode(DocumentNode node, Declared stated)
        {
            if (node.Heading is not null)
            {
                Add(new DocumentSegment(Heading,
                    node.Heading, node.Level));
                AddCode(HeadingStatement.Body(
                    node.Declaration.Except(stated), node.Shared, StatedWord(node.Heading)));
            }

            if (node is BranchNode branch)
                AddLeaves(branch);
            else
                foreach (var section in Order(node.Children))
                    AddNode(section, stated.And(node.Declaration));
        }

        void AddLeaves(BranchNode branch)
        {
            AddText("\n");
            foreach (var requirement in InReadingOrder(branch.Requirements))
                Add(new(Item, Names(requirement), Content: Claims(requirement)));
        }

        void AddText(string text) => Add(new(Raw, text));

        void AddCode(string text)
        {
            if (!string.IsNullOrEmpty(text))
                Add(new(Code, text));
        }

        void Add(DocumentSegment segment) => segments.Add(segment);
    }

    /// <summary>
    /// The requirements of a branch as they read best: least arranged first, then shortest, so a
    /// reader meets preconditions gradually. Ties fall back to names, which are stable.
    /// </summary>
    private static IEnumerable<Requirement> InReadingOrder(IReadOnlyList<Requirement> requirements)
        => requirements
            .OrderBy(requirement => requirement.Arrangement)
            .ThenBy(requirement => Fit(
                Compose(requirement.Clauses, requirement.Entry.Because), DocumentWidth).Length)
            .ThenBy(requirement => requirement.Entry.Requirement, StringComparer.Ordinal)
            .ThenBy(requirement => requirement.Signature, StringComparer.Ordinal);

    /// <summary>
    /// Sections in the order they read: whatever heads nothing first, so its content is not
    /// swallowed by the heading before it, then simplest first, then by name.
    /// </summary>
    private static DocumentNode[] Order(IEnumerable<DocumentNode> nodes)
        => [..nodes.OrderBy(node => node.HasKey)
            .ThenBy(node => node.ComplexityNumber)
            .ThenBy(node => node.Key, StringComparer.Ordinal)];

    /// What a requirement is called, without the lead word its heading already said.
    private static string Names(Requirement requirement)
    {
        var name = requirement.Entry.Requirement.AsHeading();
        return Without(StatedWord(name), name);
    }

    /// What a requirement claims — the "then" dropped, the name having said it already.
    private static ComposedText Claims(Requirement requirement)
        => Compose(requirement.Clauses, requirement.Entry.Because)
            .Without(StepFamily.Then.Keyword());
}
