using TSpec.Internal.Specification;
using static TSpec.Internal.Document.RenderPipeline.DocumentText;

namespace TSpec.Internal.Document.RenderPipeline;

internal class Layout(Document document)
{
    private DocumentSegment[]? _segments;

    internal DocumentSegment[] Segments => _segments ??= LayOut();

    private DocumentSegment[] LayOut()
    {
        List<DocumentSegment> segments = [];
        AddTitle();
        AddContent();
        return [.. segments];

        void AddTitle()
        {
            Add(new TitleSegment(document.Subject.Name.AsTitle()));
            Add(new CommentSegment(
                $"Version {document.Subject.Version}+{document.BuildId}, "
                + $"generated by TSpec from {document.SpecAssemblyName}. Do not edit by hand."));
        }

        void AddContent()
        {
            Add(new CodeSegment(document.Declared, document.Whole, Stated: null));
            if (document.Areas.Count > 0)
                AppendRequirements();
        }

        void AppendRequirements()
        {
            Add(new RulerSegment());
            foreach (var area in Order(document.Areas))
                AddNode(area, document.Declared);
        }

        void AddNode(DocumentNode node, Declared stated)
        {
            if (node.Heading is not null)
            {
                Add(new HeadingSegment(node.Heading, node.Level));
                Add(new CodeSegment(
                    node.Declaration.Except(stated), node.Shared, StatedWord(node.Heading)));
            }

            if (node is BranchNode branch)
                AddLeaves(branch);
            else
                foreach (var section in Order(node.Children))
                    AddNode(section, stated.And(node.Declaration));
        }

        void AddLeaves(BranchNode branch)
        {
            Add(new NewLineSegment());
            foreach (var requirement in InReadingOrder(branch.Requirements))
                Add(new ListItemSegment(Names(requirement), Claims(requirement)));
        }

        void Add(DocumentSegment segment) => segments.Add(segment);
    }

    private static IEnumerable<Requirement> InReadingOrder(IReadOnlyList<Requirement> requirements)
        => requirements
            .OrderBy(requirement => requirement.Arrangement)
            .ThenBy(requirement => requirement.Size)
            .ThenBy(requirement => requirement.Entry.Requirement, StringComparer.Ordinal)
            .ThenBy(requirement => requirement.Signature, StringComparer.Ordinal);

    private static DocumentNode[] Order(IEnumerable<DocumentNode> nodes)
        => [..nodes.OrderBy(node => node.HasKey)
            .ThenBy(node => node.ComplexityNumber)
            .ThenBy(node => node.Key, StringComparer.Ordinal)];

    private static string Names(Requirement requirement)
    {
        var name = requirement.Entry.Requirement.AsHeading();
        return Without(StatedWord(name), name);
    }

    private static string? StatedWord(string heading)
        => StepFamilies.Keywords.FirstOrDefault(
            word => heading.StartsWith($"{word} ", StringComparison.Ordinal));

    private static ComposedText Claims(Requirement requirement)
        => Compose(requirement.Clauses, requirement.Entry.Because)
            .Without(StepFamily.Then.Keyword());

    /// A heading's lead word is not said again below it.
    private static string Without(string? stated, string specification)
        => stated is not null && specification.StartsWith($"{stated} ", StringComparison.Ordinal)
            ? specification[(stated.Length + 1)..]
            : specification;

}