using TSpec.Internal.Specification;

namespace TSpec.Internal.Document.RenderPipeline;

internal class Layout
{
    internal static DocumentSegment[] Of(Document document)
    {
        Layout layout = new(document);
        layout.AddTitle();
        layout.AddContent();
        return [.. layout._segments];
    }

    private readonly Document _document;
    private readonly List<DocumentSegment> _segments = [];

    private Layout(Document document) => _document = document;

    private void Add(DocumentSegment segment) => _segments.Add(segment);

    private void AddTitle()
    {
        Add(new TitleSegment(_document.Subject.Name.AsTitle()));
        Add(new CommentSegment(
            $"Version {_document.Subject.Version}+{_document.BuildId}, "
            + $"generated by TSpec from {_document.SpecAssemblyName}. Do not edit by hand."));
    }

    private void AddContent()
    {
        Add(new CodeSegment(_document.Declared, _document.Whole, Stated: null));
        if (_document.Areas.Count > 0)
            AddRequirements();
    }

    private void AddRequirements()
    {
        Add(new RulerSegment());
        foreach (var area in Order(_document.Areas))
            AddNode(area, _document.Declared);
    }

    private void AddNode(DocumentNode node, Declared stated)
    {
        if (node.Heading is not null)
        {
            Add(new HeadingSegment(node.Heading, node.Level));
            Add(new CodeSegment(
                node.Declaration.Except(stated), node.Shared, StatedWord(node.Heading)));
        }

        if (node is BranchNode branch)
            AddLeaves(branch);
        else
            foreach (var section in Order(node.Children))
                AddNode(section, stated.And(node.Declaration));
    }

    private void AddLeaves(BranchNode branch)
    {
        Add(new NewLineSegment());
        foreach (var requirement in InReadingOrder(branch.Requirements))
            Add(new ListItemSegment(requirement.Name, requirement.Claim));
    }

    private static IEnumerable<Requirement> InReadingOrder(IReadOnlyList<Requirement> requirements)
        => requirements
            .OrderBy(requirement => requirement.ArrangementCount)
            .ThenBy(requirement => requirement.Size)
            .ThenBy(requirement => requirement.Entry.Requirement, StringComparer.Ordinal)
            .ThenBy(requirement => requirement.Signature, StringComparer.Ordinal);

    private static DocumentNode[] Order(IEnumerable<DocumentNode> nodes)
        => [..nodes.OrderBy(node => node.HasKey)
            .ThenBy(node => node.ComplexityNumber)
            .ThenBy(node => node.Key, StringComparer.Ordinal)];

    internal static string? StatedWord(string heading)
        => StepFamilies.Keywords.FirstOrDefault(
            word => heading.StartsWith($"{word} ", StringComparison.Ordinal));
}