using TSpec.Assert;
using TSpec.Internal.Document;

namespace TSpec.Test.Internal.Document;

/// <summary>
/// The whole resolution chain — manifest, subject, project directory, rendering — against a
/// real directory. The fixture constructor adds only the lookup of the spec assembly's name.
/// </summary>
public class WhenPrepareDocument : Spec
{
    [Fact]
    public void ThenTargetTheProjectRoot()
    {
        using var project = new TempProject("MyHotel.Spec", DepsJson.MyHotelSpec);
        PendingDocument.Prepare("MyHotel.Spec", project.BaseDirectory)
            .Path.Is(Path.Combine(project.Root, "SPECIFICATION.md"));
    }

    [Fact]
    public void ThenRenderTheSubjectItResolved()
    {
        using var project = new TempProject("MyHotel.Spec", DepsJson.MyHotelSpec);
        PendingDocument.Prepare("MyHotel.Spec", project.BaseDirectory)
            .Render([]).Does().Contain("# My Hotel").and.Contain("Version 0.1.0");
    }

    /// <summary>
    /// The id names the source the subject was built from, and it is the subject's rather than the
    /// spec project's. Changing a method body leaves the spec assembly compiling to the same bytes,
    /// so an id taken from there would sit still through the very change it exists to catch.
    /// </summary>
    [Fact]
    public void ThenIdentifyTheSourceTheSubjectWasBuiltFrom()
    {
        using var project = new TempProject("MyHotel.Spec", DepsJson.MyHotelSpec);
        var subject = project.CopyAssemblyAs("MyHotel", typeof(Spec).Assembly);
        PendingDocument.Prepare("MyHotel.Spec", project.BaseDirectory)
            .Render([]).Does().Contain($"Version 0.1.0+{SourceDigest.Of(subject)},");
    }

    /// <summary>
    /// Everything the subject is built on, not the subject's own assembly alone. A rule can sit in
    /// a project below the subject and change there without a line of the subject's own source
    /// moving, and the document would describe code that is no longer there.
    /// </summary>
    [Fact]
    public void ThenIdentifyTheSourceOfEverythingBelowTheSubject()
    {
        using var project = new TempProject("MyHotel.Spec", DepsJson.MyHotelSpec);
        var subject = project.CopyAssemblyAs("MyHotel", typeof(Spec).Assembly);
        var below = project.CopyAssemblyAs("MyHotel.Persistence", typeof(Spec).Assembly);
        PendingDocument.Prepare("MyHotel.Spec", project.BaseDirectory)
            .Render([]).Does().Contain($"Version 0.1.0+{SourceDigest.Of([subject, below])},");
    }

    /// <summary>A subject built without debug information leaves no source to name.</summary>
    [Fact]
    public void GivenTheSubjectCarriesNoDebugInformation_ThenStateOnlyItsVersion()
    {
        using var project = new TempProject("MyHotel.Spec", DepsJson.MyHotelSpec);
        PendingDocument.Prepare("MyHotel.Spec", project.BaseDirectory)
            .Render([]).Does().Contain("Version 0.1.0, generated by TSpec");
    }

    [Fact]
    public void ThenWriteWhatItPrepared()
    {
        using var project = new TempProject("MyHotel.Spec", DepsJson.MyHotelSpec);
        var document = PendingDocument.Prepare("MyHotel.Spec", project.BaseDirectory);
        document.Write([]);
        File.ReadAllText(document.Path).Is(document.Render([]));
    }

    [Fact]
    public void GivenNoDependencyManifest_ThenFail()
    {
        using var project = new TempProject("MyHotel.Spec");
        var error = Xunit.Assert.Throws<SetupFailed>(
            () => PendingDocument.Prepare("MyHotel.Spec", project.BaseDirectory));
        error.Message.Does().Contain("MyHotel.Spec.deps.json");
    }

    [Fact]
    public void GivenNoProjectFile_ThenFail()
    {
        using var project = new TempProject("MyHotel.Spec", DepsJson.MyHotelSpec, withProjectFile: false);
        Xunit.Assert.Throws<SetupFailed>(
            () => PendingDocument.Prepare("MyHotel.Spec", project.BaseDirectory));
    }
}
