using TSpec.Assert;
using TSpec.Internal.Document;
using TSpec.Internal.Specification;

namespace TSpec.Test.Internal.Document;

public class WhenRenderDocument : Spec
{
    private const string Header =
        "# MyHotel\n"
        + "\n"
        + "Version 0.1.0, hash 4f2a9c1e\n"
        + "\n"
        + "<!-- Generated by TSpec from MyHotel.Spec. Do not edit by hand. -->\n";

    private static readonly SpecificationSubject _myHotel = new("MyHotel", "0.1.0");

    private static readonly SpecificationEntry _respondOk = new(
        "WhenGetVersion", "GivenNothing", "ThenRespondOk",
        Sentences(
            "using owned CreateClient",
            "when api.GetAsync(\"/version\")",
            "then Result.StatusCode is HttpStatusCode.OK"));

    /// The document takes described steps, so a test that is about layout rather than about
    /// description supplies the simplest step there is: one sentence per line.
    private static SpecificationStep[] Sentences(params string[] sentences)
        => [.. sentences.Select(sentence => new SpecificationStep(StepLayout.Sentence) { Body = sentence })];

    private static string Render(params SpecificationEntry[] entries)
        => DocumentRenderer.Render(_myHotel, "MyHotel.Spec", "4f2a9c1e", entries);

    [Fact] public void GivenNoEntries_ThenRenderTheHeaderAlone() => Render().Is(Header);

    [Fact]
    public void ThenNameTheBuildTheDocumentCameFrom()
        => Render().Does().Contain("Version 0.1.0, hash 4f2a9c1e");

    [Fact]
    public void ThenRenderTheRequirementUnderItsSubject()
        => Render(_respondOk).Is(
            Header
            + "\n"
            + "## WhenGetVersion\n"
            + "\n"
            + "### GivenNothing.ThenRespondOk\n"
            + "\n"
            + "```\n"
            + "Using owned CreateClient\n"
            + "When api.GetAsync(\"/version\")\n"
            + "Then Result.StatusCode is HttpStatusCode.OK\n"
            + "```\n");

    [Fact]
    public void GivenNoBranch_ThenHeadTheRequirementByNameAlone()
        => Render(_respondOk with { Branch = "" }).Does().Contain("### ThenRespondOk\n");

    /// <summary>Two requirements of one subject share a single subject heading.</summary>
    [Fact]
    public void ThenGroupRequirementsBySubject()
    {
        var document = Render(_respondOk, _respondOk with { Requirement = "ThenReturnVersion" });
        document.Split("## WhenGetVersion").Length.Is(2);
        document.Does().Contain("### GivenNothing.ThenRespondOk").and.Contain("### GivenNothing.ThenReturnVersion");
    }

    [Fact]
    public void GivenEntriesOutOfOrder_ThenSortThem()
        => Render(_respondOk with { Requirement = "ThenB" }, _respondOk with { Requirement = "ThenA" })
            .Does().Contain("### GivenNothing.ThenA").and.Contain("### GivenNothing.ThenB");

    /// <summary>A theory reports once per case; identical text must not repeat in the document.</summary>
    [Fact]
    public void GivenDuplicateEntries_ThenRenderOne()
        => Render(_respondOk, _respondOk).Is(Render(_respondOk));

    /// <summary>The specification is built with Environment.NewLine, so it comes back CRLF on Windows.</summary>
    [Fact]
    public void ThenNormaliseLineEndingsToLf()
        => Render(_respondOk with { Steps = Sentences("when a", "then b") })
            .Does().Contain("```\nWhen a\nThen b\n```").and.not.Contain("\r");

    // ----------- What every requirement of a group opens with is stated once for the group

    private static SpecificationStep Using(string body)
        => new(StepLayout.SentenceOrPhrase) { Family = StepFamily.Using, Body = body };

    private static SpecificationStep Act(string body)
        => new(StepLayout.SentenceOrPhrase) { Family = StepFamily.When, Body = body };

    /// An assertion heading its own line, which is the one clause with no family.
    private static SpecificationStep Claim(string body)
        => new(StepLayout.Sentence) { Body = body };

    private static SpecificationEntry Requirement(
        string subject, string name, params SpecificationStep[] steps)
        => new(subject, "", name, steps);

    /// Two subjects that share their arrangement but each have their own action.
    private static SpecificationEntry[] TwoSubjects()
        => [.. new[] { "a", "b", "c" }.Select(name =>
                Requirement("WhenGetRoom", $"Then{name}",
                    Using("api"), Act("get"), Claim($"then {name}"))),
            .. new[] { "d", "e", "f" }.Select(name =>
                Requirement("WhenAddRoom", $"Then{name}",
                    Using("api"), Act("post"), Claim($"then {name}")))];

    /// <summary>Shared by every requirement in the document, so it rises above the subjects.</summary>
    [Fact]
    public void GivenEveryRequirementOpensAlike_ThenStateThatOnceForTheDocument()
        => Render(TwoSubjects()).Does()
            .Contain("Do not edit by hand. -->\n\n```\nUsing api\n```\n\n## WhenAddRoom");

    /// <summary>Shared within one subject only, so it settles at that subject's heading.</summary>
    [Fact]
    public void GivenOneSubjectOpensAlike_ThenStateThatOnceForTheSubject()
        => Render(TwoSubjects()).Does()
            .Contain("## WhenAddRoom\n\n```\nWhen post\n```\n")
            .and.Contain("## WhenGetRoom\n\n```\nWhen get\n```\n")
            .and.Contain("### Thena\n\n```\nThen a\n```\n");

    /// <summary>
    /// An assertion is the claim a requirement exists to make. Two requirements agreeing on one
    /// is worth seeing, so it stays in both blocks however often it repeats.
    /// </summary>
    [Fact]
    public void GivenEveryRequirementClaimsTheSame_ThenStillStateItInEachBlock()
        => Render([.. new[] { "a", "b", "c" }.Select(name =>
                Requirement("WhenGetRoom", $"Then{name}", Claim("then same"), Claim($"then {name}")))])
            .Split("Then same").Length.Is(4);

    /// <summary>Two requirements are not repetition worth factoring out.</summary>
    [Fact]
    public void GivenFewerThanThreeRequirements_ThenLeaveTheOpeningInPlace()
        => Render(TwoSubjects()[..2]).Does()
            .Contain("```\nUsing api\nWhen get\nThen a\n```")
            .and.not.Contain("-->\n\n```");

    [Fact]
    public void GivenOneRequirementOpensDifferently_ThenLeaveTheOpeningInPlace()
    {
        var requirements = TwoSubjects()[..3];
        requirements[2] = requirements[2] with { Steps = [Using("other"), Act("get"), Claim("then c")] };
        Render(requirements).Does().not.Contain("-->\n\n```");
    }

    /// <summary>Hoisting must never empty a block, so a requirement that is only the opening blocks it.</summary>
    [Fact]
    public void GivenARequirementIsNothingButTheSharedOpening_ThenLeaveTheOpeningInPlace()
    {
        var requirements = TwoSubjects()[..3];
        requirements[2] = requirements[2] with { Steps = [Using("api")] };
        Render(requirements).Does().not.Contain("-->\n\n```");
    }
}
