using TSpec.Assert;
using TSpec.Internal.Document;
using TSpec.Internal.Document.RenderPipeline;
using TSpec.Internal.Specification;

namespace TSpec.Test.Internal.Document;

/// <summary>
/// The README of the specification folder: the entry point the folder's files share, and a table
/// with one row per file saying what it covers and how much — which is what a reviewer reads in a
/// diff to see where a change landed.
/// </summary>
public class WhenRenderIndex : Spec
{
    private static readonly SpecificationSubject _myHotel = new("MyHotel", "0.1.0");

    private static SpecificationClause Clause(StepLayout layout, StepFamily family, string body)
        => new([new SpecificationStep(layout) { Family = family, Body = body }]);

    private static SpecificationClause Using(string body)
        => Clause(StepLayout.SentenceOrPhrase, StepFamily.Using, body);

    private static SpecificationClause Claim(string body)
        => Clause(StepLayout.Sentence, StepFamily.None, body);

    private static SpecificationEntry In(
        string @namespace, string subject, string branch, string name, params SpecificationClause[] clauses)
        => new(subject, branch, name, clauses.Length == 0 ? [Claim(name.AsWords())] : clauses,
            Namespace: @namespace);

    private static SpecificationEntry[] TwoFolders() => [
        In("MyHotel.Spec.Rooms", "WhenAddRoom", "GivenNoSuchRoom", "ThenA"),
        In("MyHotel.Spec.Rooms", "WhenAddRoom", "GivenTheRoomExists", "ThenB"),
        In("MyHotel.Spec.Rooms", "WhenAddRoom", "GivenTheRoomExists", "ThenC"),
        In("MyHotel.Spec.Rooms", "WhenGetRoom", "", "ThenD"),
        In("MyHotel.Spec.Bookings", "WhenBook", "", "ThenE")];

    private static IReadOnlyList<SpecificationFile> Files(params SpecificationEntry[] entries)
        => DocumentRenderer.Render(_myHotel, "MyHotel.Spec", entries);

    private static string Index(params SpecificationEntry[] entries)
        => Files(entries).Single(file => file.Name == "README").Content;

    /// <summary>
    /// First among the files, being the one to open first — and always there, so the folder never
    /// holds one file with nothing to say where it fits.
    /// </summary>
    [Fact]
    public void ThenWriteAReadmeFirst()
        => Files(TwoFolders()).Select(file => file.Name).Is().EqualTo(["README", "Bookings", "Rooms"]);

    [Fact]
    public void ThenTitleItAsTheProject()
        => Index(TwoFolders()).Does().StartWith(
            "# My Hotel\n\n<!-- Version 0.1.0, generated by TSpec from MyHotel.Spec. Do not edit by hand. -->\n");

    /// <summary>
    /// One row per file: the file as a link, and how many acts, cases and requirements it holds,
    /// each counted as the file shows them — a theory once, a requirement every branch repeats once
    /// where it is listed, a nested given at each heading it takes. The last row sums them all, in
    /// italics so it reads as a different kind of row.
    /// </summary>
    [Fact]
    public void ThenTableOneRowPerFileAndOneForAll()
        => Index(TwoFolders()).Does().Contain(
            "| Specification           | When | Given | Then |\n"
            + "|-------------------------|-----:|------:|-----:|\n"
            + "| [Bookings](Bookings.md) |    1 |     0 |    1 |\n"
            + "| [Rooms](Rooms.md)       |    2 |     2 |    4 |\n"
            + "| *All*                   |  *3* |   *2* |  *5* |\n");

    [Fact]
    public void GivenANestedGiven_ThenCountEachHeading()
        => Index(
            In("MyHotel.Spec.Rooms", "WhenGetRoom", "GivenTheRoomExists.WithItems", "ThenA"),
            In("MyHotel.Spec.Rooms", "WhenGetRoom", "GivenTheRoomExists.WithNoItems", "ThenB"))
            .Does().Contain("| [Rooms](Rooms.md) |    1 |     3 |    2 |");

    [Fact]
    public void GivenATheory_ThenCountItOnce()
        => Index(
            In("MyHotel.Spec.Rooms", "WhenGetRoom", "", "ThenA") with { Row = new(0, ["n"], ["1"]) },
            In("MyHotel.Spec.Rooms", "WhenGetRoom", "", "ThenA") with { Row = new(1, ["n"], ["2"]) })
            .Does().Contain("| [Rooms](Rooms.md) |    1 |     0 |    1 |");

    /// <summary>What every file states at its top is stated here once, above the table.</summary>
    [Fact]
    public void GivenEveryRequirementOpensAlike_ThenStateThatAboveTheTable()
        => Index([.. TwoFolders().Select(entry => entry with
                { Clauses = [Using("api"), .. entry.Clauses], SubjectUnderTest = "Hotel" })])
            .Does().Contain("-->\n```\nSubject under test: Hotel\nUsing api\n```\n\n| Specification");

    [Fact]
    public void GivenTheFilesOpenDifferently_ThenStateNothingAboveTheTable()
        => Index(TwoFolders()).Does().Contain("-->\n\n| Specification");

    /// <summary>
    /// What the project says of itself opens the index, before what the tests say of it: the one
    /// sentence a person wrote about what the module is, ahead of what holds throughout and the
    /// counts.
    /// </summary>
    [Fact]
    public void GivenTheSubjectIsDescribed_ThenOpenWithTheDescription()
        => DocumentRenderer.Render(new("MyHotel", "0.1.0", "A hotel booking API."), "MyHotel.Spec",
            [.. TwoFolders().Select(entry => entry with { SubjectUnderTest = "Hotel" })])
            .Single(file => file.Name == "README").Content
            .Does().Contain("-->\n\nA hotel booking API.\n\n`Subject under test: Hotel`\n\n| Specification");

    [Fact]
    public void GivenAFolderIsNamedReadme_ThenFail()
        => Xunit.Assert.Throws<SetupFailed>(() => Files(In("MyHotel.Spec.README", "WhenX", "", "ThenA")))
            .Message.Does().Contain("README");

    [Fact]
    public void GivenNoEntries_ThenWriteNoReadme() => Files().Is().Empty();
}
