using TSpec.Assert;
using TSpec.Internal.Document;

namespace TSpec.Test.Internal.Document;

/// <summary>
/// The whole resolution chain — manifest, subject, project directory, rendering — against a
/// real directory. The fixture constructor adds only the lookup of the spec assembly's name.
/// </summary>
public class WhenPrepareDocument : Spec
{
    [Fact]
    public void ThenTargetTheProjectRoot()
    {
        using var project = new TempProject("MyHotel.Spec", DepsJson.MyHotelSpec);
        PendingDocument.Prepare("MyHotel.Spec", project.BaseDirectory)
            .Path.Is(Path.Combine(project.Root, "SPECIFICATION.md"));
    }

    [Fact]
    public void ThenRenderTheSubjectItResolved()
    {
        using var project = new TempProject("MyHotel.Spec", DepsJson.MyHotelSpec);
        PendingDocument.Prepare("MyHotel.Spec", project.BaseDirectory)
            .Render([]).Does().Contain("# My Hotel").and.Contain("Version 0.1.0");
    }

    /// <summary>
    /// The header states the subject's version and nothing more. The document renders what the
    /// tests claim, so what it has to stay in step with is the tests — and the body already says
    /// that in full, on every line, which is what the freshness diff compares. Naming the
    /// implementation's source as well would have the header speak for a thing the document does
    /// not describe, and move on changes that alter no claim in it.
    /// </summary>
    [Fact]
    public void ThenStateTheSubjectVersionAlone()
    {
        using var project = new TempProject("MyHotel.Spec", DepsJson.MyHotelSpec);
        project.CopyAssemblyAs("MyHotel", typeof(Spec).Assembly);
        PendingDocument.Prepare("MyHotel.Spec", project.BaseDirectory)
            .Render([]).Does().Contain("Version 0.1.0, generated by TSpec");
    }

    [Fact]
    public void ThenWriteWhatItPrepared()
    {
        using var project = new TempProject("MyHotel.Spec", DepsJson.MyHotelSpec);
        var document = PendingDocument.Prepare("MyHotel.Spec", project.BaseDirectory);
        document.Write([]);
        File.ReadAllText(document.Path).Is(document.Render([]));
    }

    [Fact]
    public void GivenNoDependencyManifest_ThenFail()
    {
        using var project = new TempProject("MyHotel.Spec");
        var error = Xunit.Assert.Throws<SetupFailed>(
            () => PendingDocument.Prepare("MyHotel.Spec", project.BaseDirectory));
        error.Message.Does().Contain("MyHotel.Spec.deps.json");
    }

    [Fact]
    public void GivenNoProjectFile_ThenFail()
    {
        using var project = new TempProject("MyHotel.Spec", DepsJson.MyHotelSpec, withProjectFile: false);
        Xunit.Assert.Throws<SetupFailed>(
            () => PendingDocument.Prepare("MyHotel.Spec", project.BaseDirectory));
    }
}
