using TSpec.Assert;
using TSpec.Internal.Document;

namespace TSpec.Test.Internal.Document;

public class WhenRenderDocument : Spec
{
    [Fact]
    public void ThenNameTheSubjectAndItsVersion()
        => DocumentRenderer.Render(new SpecificationSubject("MyHotel", "0.1.0"), "MyHotel.Spec")
            .Is(
                "# MyHotel\n"
                + "\n"
                + "Version 0.1.0\n"
                + "\n"
                + "<!-- Generated by TSpec from MyHotel.Spec. Do not edit by hand. -->\n");
}
