using TSpec.Assert;
using TSpec.Internal.Document;
using TSpec.Internal.Specification;

namespace TSpec.Test.Internal.Document;

/// <summary>
/// The whole resolution chain — manifest, subject, project directory, rendering — against a
/// real directory. The fixture constructor adds only the lookup of the spec assembly's name.
/// </summary>
public class WhenPrepareSpecification : Spec
{
    private static SpecificationEntry In(string @namespace, string subject)
        => new(subject, "", "ThenA",
            [new([new SpecificationStep(StepLayout.Sentence) { Body = "then a" }])],
            Namespace: @namespace);

    private static readonly SpecificationEntry _atRoot = In("MyHotel.Spec", "WhenGetVersion");
    private static readonly SpecificationEntry _inRooms = In("MyHotel.Spec.Rooms", "WhenAddRoom");

    [Fact]
    public void ThenTargetTheSpecificationFolderOfTheProject()
    {
        using var project = new TempProject("MyHotel.Spec", DepsJson.MyHotelSpec);
        PendingSpecification.Prepare("MyHotel.Spec", project.BaseDirectory)!
            .Directory.Is(Path.Combine(project.Root, "_specification"));
    }

    [Fact]
    public void ThenRenderTheSubjectItResolved()
    {
        using var project = new TempProject("MyHotel.Spec", DepsJson.MyHotelSpec);
        PendingSpecification.Prepare("MyHotel.Spec", project.BaseDirectory)!
            .Render([_atRoot]).Documents().Single().Content.Does().Contain("# My Hotel").and.Contain("Version 0.1.0");
    }

    /// <summary>
    /// The header states the subject's version and nothing more. The document renders what the
    /// tests claim, so what it has to stay in step with is the tests — and the body already says
    /// that in full, on every line, which is what the freshness diff compares. Naming the
    /// implementation's source as well would have the header speak for a thing the document does
    /// not describe, and move on changes that alter no claim in it.
    /// </summary>
    [Fact]
    public void ThenStateTheSubjectVersionAlone()
    {
        using var project = new TempProject("MyHotel.Spec", DepsJson.MyHotelSpec);
        project.CopyAssemblyAs("MyHotel", typeof(Spec).Assembly);
        PendingSpecification.Prepare("MyHotel.Spec", project.BaseDirectory)!
            .Render([_atRoot]).Documents().Single().Content.Does().Contain("Version 0.1.0, generated by TSpec");
    }

    /// <summary>
    /// The subject's own description, as its project file states it and its assembly carries it.
    /// TSpec is the one project whose assembly this process is sure to have loaded.
    /// </summary>
    [Fact]
    public void ThenDescribeTheSubjectAsItsProjectDoes()
    {
        using var project = new TempProject("TSpec.Spec", DepsJson.TSpecSpec);
        PendingSpecification.Prepare("TSpec.Spec", project.BaseDirectory)!
            .Subject.Description.Is(SubjectDescription.Of("TSpec"));
    }

    /// A subject that is not loaded, or states no description, heads its index with none.
    [Fact]
    public void GivenTheSubjectIsNotDescribed_ThenNone()
    {
        using var project = new TempProject("MyHotel.Spec", DepsJson.MyHotelSpec);
        PendingSpecification.Prepare("MyHotel.Spec", project.BaseDirectory)!
            .Subject.Description.Is().Null();
    }

    [Fact]
    public void ThenWriteEachFileItPrepared()
    {
        using var project = new TempProject("MyHotel.Spec", DepsJson.MyHotelSpec);
        var specification = PendingSpecification.Prepare("MyHotel.Spec", project.BaseDirectory)!;
        specification.Write([_atRoot, _inRooms]);
        foreach (var file in specification.Render([_atRoot, _inRooms]))
            File.ReadAllText(Path.Combine(specification.Directory, file.FileName)).Is(file.Content);
    }

    /// <summary>
    /// A full run replaces the folder's contents: a file for a folder that was renamed or removed
    /// would otherwise stay on, stating requirements nothing runs any more.
    /// </summary>
    [Fact]
    public void GivenAFileFromAnEarlierRun_ThenRemoveIt()
    {
        using var project = new TempProject("MyHotel.Spec", DepsJson.MyHotelSpec);
        var specification = PendingSpecification.Prepare("MyHotel.Spec", project.BaseDirectory)!;
        Directory.CreateDirectory(specification.Directory);
        var stale = Path.Combine(specification.Directory, "Bookings.md");
        File.WriteAllText(stale, "# Bookings");
        specification.Write([_inRooms]);
        File.Exists(stale).Is(false);
        File.Exists(Path.Combine(specification.Directory, "Rooms.md")).Is(true);
    }

    /// <summary>
    /// A checkout that holds the files as CRLF would otherwise report every one of them modified
    /// after a run, though nothing in them changed. What is on disk decides, not the environment.
    /// </summary>
    [Fact]
    public void GivenAFileWrittenWithCarriageReturns_ThenKeepThem()
    {
        using var project = new TempProject("MyHotel.Spec", DepsJson.MyHotelSpec);
        var specification = PendingSpecification.Prepare("MyHotel.Spec", project.BaseDirectory)!;
        Directory.CreateDirectory(specification.Directory);
        File.WriteAllText(Path.Combine(specification.Directory, "Rooms.md"), "# Rooms\r\n");
        specification.Write([_inRooms]);
        File.ReadAllText(Path.Combine(specification.Directory, "Rooms.md"))
            .Is(specification.Render([_inRooms]).Documents().Single().Content.Replace("\n", "\r\n"));
    }

    /// A file the folder does not hold yet has no endings to keep, and is written as composed.
    [Fact]
    public void GivenANewFile_ThenWriteItAsComposed()
    {
        using var project = new TempProject("MyHotel.Spec", DepsJson.MyHotelSpec);
        var specification = PendingSpecification.Prepare("MyHotel.Spec", project.BaseDirectory)!;
        specification.Write([_inRooms]);
        File.ReadAllText(Path.Combine(specification.Directory, "Rooms.md"))
            .Is(specification.Render([_inRooms]).Documents().Single().Content);
    }

    [Fact]
    public void GivenNoDependencyManifest_ThenFail()
    {
        using var project = new TempProject("MyHotel.Spec");
        var error = Xunit.Assert.Throws<SetupFailed>(
            () => PendingSpecification.Prepare("MyHotel.Spec", project.BaseDirectory));
        error.Message.Does().Contain("MyHotel.Spec.deps.json");
    }

    /// <summary>
    /// Nothing to write into, and nothing to fail either: no test claims the specification, so an
    /// unlocatable project leaves the run alone and says why.
    /// </summary>
    [Fact]
    public void GivenNoProjectFile_ThenPrepareNothing()
    {
        using var project = new TempProject("MyHotel.Spec", DepsJson.MyHotelSpec, withProjectFile: false);
        PendingSpecification.Prepare("MyHotel.Spec", project.BaseDirectory).Is().Null();
    }

    /// <summary>
    /// The source files decide, not the build output: a project built to an artifacts path outside
    /// its own tree still writes its specification beside its project file.
    /// </summary>
    [Fact]
    public void GivenTheOutputIsOutsideTheSourceTree_ThenTargetTheProjectTheSourcesAreIn()
    {
        using var project = new TempProject("MyHotel.Spec");
        using var artifacts = new TempProject("MyHotel.Spec", DepsJson.MyHotelSpec, withProjectFile: false);
        PendingSpecification.Prepare(
            "MyHotel.Spec", artifacts.BaseDirectory, [project.AddSource("Rooms", "WhenAddRoom.cs")])!
            .Directory.Is(Path.Combine(project.Root, "_specification"));
    }
}
