using TSpec.Assert;
using TSpec.Internal.Document;
using TSpec.Internal.Document.RenderPipeline;
using TSpec.Internal.Specification;

namespace TSpec.Test.Internal.Document;

public class WhenRenderDocument : Spec
{
    private const string Header =
        "# My Hotel\n"
        + "\n"
        + "<!-- Version 0.1.0, generated by TSpec from MyHotel.Spec. Do not edit by hand. -->\n";

    /// What separates the document's own block from the sections below it.
    private const string Rule = "\n---\n";

    private static readonly SpecificationSubject _myHotel = new("MyHotel", "0.1.0");

    private static readonly SpecificationEntry _respondOk = new(
        "WhenGetVersion", "GivenNothing", "ThenRespondOk",
        Sentences(
            "using owned CreateClient",
            "when api.GetAsync(\"/version\")",
            "then Result.StatusCode is HttpStatusCode.OK"));

    /// The document takes described clauses, so a test that is about layout rather than about
    /// description supplies the simplest clause there is: one sentence, saying one thing.
    private static SpecificationClause[] Sentences(params string[] sentences)
        => [.. sentences.Select(sentence => Clause(StepLayout.Sentence, StepFamily.None, sentence))];

    private static SpecificationClause Clause(StepLayout layout, StepFamily family, string body)
        => new([new SpecificationStep(layout) { Family = family, Body = body }]);

    private static string Render(params SpecificationEntry[] entries)
        => DocumentRenderer.Render(_myHotel, "MyHotel.Spec", entries);

    [Fact] public void GivenNoEntries_ThenRenderTheHeaderAlone() => Render().Is(Header);

    /// <summary>
    /// Sections head at the title's own level, there being no level above it, so a rule closes what
    /// the document says of itself — without one the first section would read as a sibling of the
    /// title. It sits under that whole block rather than under the title alone, which would rule
    /// between two things that are one: the document's name and what holds throughout it.
    /// </summary>
    [Fact]
    public void ThenRuleOffWhatTheDocumentSaysOfItself()
        => Render(_respondOk with { SubjectUnderTest = "Hotel" }).Does()
            .Contain("`Subject under test: Hotel`\n\n---\n\n## When get version\n");

    /// <summary>
    /// The subject's version, and nothing that names its source. What the document has to stay in
    /// step with is the tests it renders, and the body says that in full on every line.
    /// </summary>
    [Fact]
    public void ThenStateTheSubjectVersion()
        => Render().Does().Contain("Version 0.1.0, generated by TSpec");

    /// <summary>
    /// A project named for a layer is dotted — "MyHotel.Core" — and there the dot separates parts of
    /// one name, not one sentence from the next. A branch path is the opposite case, which is why
    /// <c>AsHeading</c> splits it into sentences and a title does not.
    /// </summary>
    [Fact]
    public void GivenADottedSubjectName_ThenTitleItAsOneName()
        => DocumentRenderer.Render(new("MyHotel.Core", "0.1.0"), "MyHotel.Core.Spec", [])
            .Does().StartWith("# My Hotel Core\n");

    [Fact]
    public void ThenRenderTheRequirementUnderItsSubject()
        => Render(_respondOk).Is(
            Header
            + Rule
            + "\n"
            + "## When get version\n"
            + "\n"
            + "### Given nothing\n"
            + "\n"
            + "- **respond ok**\n"
            + "  ```\n"
            + "  Using owned CreateClient\n"
            + "  When api.GetAsync(\"/version\")\n"
            + "  Then Result.StatusCode is HttpStatusCode.OK\n"
            + "  ```\n");

    /// <summary>
    /// A requirement is an item of a list wherever it sits, so a subject with no branch loses a
    /// level of nesting rather than a level of heading.
    /// </summary>
    [Fact]
    public void GivenNoBranch_ThenListTheRequirementUnderTheSubject()
        => Render(_respondOk with { Branch = "" }).Does()
            .Contain("## When get version\n\n- **respond ok**\n").and.not.Contain("###");

    /// <summary>Two requirements of one subject share a single subject heading.</summary>
    [Fact]
    public void ThenGroupRequirementsBySubject()
    {
        var document = Render(_respondOk, _respondOk with { Requirement = "ThenReturnVersion" });
        document.Split("## When get version").Length.Is(2);
        document.Does().Contain("- **respond ok**").and.Contain("- **return version**");
        document.Split("### Given nothing\n").Length.Is(2);
    }

    [Fact]
    public void GivenEntriesOutOfOrder_ThenSortThem()
        => Render(_respondOk with { Requirement = "ThenB" }, _respondOk with { Requirement = "ThenA" })
            .Does().Contain("- **a**\n").and.Contain("- **b**\n");

    /// <summary>A theory reports once per case; identical text must not repeat in the document.</summary>
    [Fact]
    public void GivenDuplicateEntries_ThenRenderOne()
        => Render(_respondOk, _respondOk).Is(Render(_respondOk));

    /// <summary>The specification is built with Environment.NewLine, so it comes back CRLF on Windows.</summary>
    [Fact]
    public void ThenNormaliseLineEndingsToLf()
        => Render(_respondOk with { Clauses = Sentences("when a", "then b") })
            .Does().Contain("When a\n  Then b").and.not.Contain("\r");

    // ----------- A heading states the context, and the requirements under it are a list

    private static SpecificationClause Using(string body)
        => Clause(StepLayout.SentenceOrPhrase, StepFamily.Using, body);

    private static SpecificationClause Act(string body)
        => Clause(StepLayout.SentenceOrPhrase, StepFamily.When, body);

    /// An assertion heading its own line, which is the one clause with no family.
    private static SpecificationClause Claim(string body)
        => Clause(StepLayout.Sentence, StepFamily.None, body);

    private static SpecificationClause Condition(string body)
        => Clause(StepLayout.SentenceOrPhrase, StepFamily.Having, body);

    private static SpecificationEntry Requirement(
        string subject, string name, params SpecificationClause[] clauses)
        => new(subject, "", name, clauses);

    /// <summary>
    /// One statement under a heading is written inline, where a fence would be an element of its own
    /// paying a margin above and below for a single line — and it drops the word the heading has
    /// already said.
    /// </summary>
    [Fact]
    public void GivenAHeadingStatesOneClause_ThenWriteItInlineWithoutTheWordItSaid()
        => Render(
            Requirement("WhenGetRoom", "ThenA", Act("get"), Claim("then a")),
            Requirement("WhenAddRoom", "ThenB", Act("post"), Claim("then b")))
            .Does().Contain("## When get room\n`get`\n");

    /// <summary>
    /// A requirement is an item of a list: its name reads the claim and the claim stands beside it,
    /// neither of them saying the "then" that the item's place in the list says already.
    /// </summary>
    [Fact]
    public void ThenWriteARequirementAsAListItem()
        => Render(Requirement("WhenGetRoom", "ThenRespondOk", Act("get"), Claim("then Result is OK")))
            .Does().Contain("- **respond ok** — `Result is OK`\n");

    /// <summary>
    /// A requirement that states more than its claim keeps the fence, indented into its own item so
    /// that the list survives it — and keeps its lead words, which are what orders the statements.
    /// </summary>
    [Fact]
    public void GivenARequirementStatesSeveralThings_ThenFenceThemInsideItsItem()
        => Render(
            Requirement("WhenGetRoom", "ThenA", Act("get"), Condition("post"), Claim("then a")),
            Requirement("WhenGetRoom", "ThenB", Act("get"), Claim("then b")))
            .Does().Contain("- **a**\n  ```\n  Having post\n  Then a\n  ```\n");

    // ----------- What every requirement of a group opens with is stated once for the group

    /// <summary>
    /// A condition shared by a branch's requirements belongs at the branch heading, which is the
    /// one place naming it agrees with what it says.
    /// </summary>
    [Fact]
    public void GivenABranchOpensAlike_ThenStateThatOnceForTheBranch()
    {
        SpecificationEntry OfBranch(string branch, string name, params SpecificationClause[] own)
            => new("WhenGetRoom", branch, name, [Using("api"), Act("get"), .. own]);
        Render(
            OfBranch("GivenTheRoomExists", "ThenA", Condition("post"), Claim("then a")),
            OfBranch("GivenTheRoomExists", "ThenB", Condition("post"), Claim("then b")),
            OfBranch("GivenNoSuchRoom", "ThenC", Claim("then c")),
            OfBranch("GivenNoSuchRoom", "ThenD", Claim("then d")))
            .Does()
            .Contain("### Given the room exists\n`Having post`\n")
            .and.Contain("- **a** — `a`\n")
            .and.Contain("### Given no such room\n\n- **c** — `c`\n");
    }

    /// Two subjects that share their arrangement but each have their own action.
    private static SpecificationEntry[] TwoSubjects()
        => [.. new[] { "a", "b", "c" }.Select(name =>
                Requirement("WhenGetRoom", $"Then{name}",
                    Using("api"), Act("get"), Claim($"then {name}"))),
            .. new[] { "d", "e", "f" }.Select(name =>
                Requirement("WhenAddRoom", $"Then{name}",
                    Using("api"), Act("post"), Claim($"then {name}")))];

    /// <summary>Shared by every requirement in the document, so it rises above the subjects.</summary>
    [Fact]
    public void GivenEveryRequirementOpensAlike_ThenStateThatOnceForTheDocument()
        => Render(TwoSubjects()).Does()
            .Contain("Do not edit by hand. -->\n`Using api`\n\n---\n\n## When add room");

    /// <summary>Shared within one subject only, so it settles at that subject's heading.</summary>
    [Fact]
    public void GivenOneSubjectOpensAlike_ThenStateThatOnceForTheSubject()
        => Render(TwoSubjects()).Does()
            .Contain("## When add room\n`post`\n")
            .and.Contain("## When get room\n`get`\n")
            .and.Contain("- **Thena** — `a`\n");

    /// <summary>
    /// An assertion is the claim a requirement exists to make. Two requirements agreeing on one is
    /// worth seeing, so it stays in both blocks however often it repeats — a requirement is the
    /// smallest thing that may rise, and what it states never rises without it.
    /// </summary>
    [Fact]
    public void GivenEveryRequirementClaimsTheSame_ThenStillStateItInEachBlock()
        => Render([.. new[] { "a", "b", "c" }.Select(name =>
                Requirement("WhenGetRoom", $"Then{name}", Claim("then same"), Claim($"then {name}")))])
            .Split("same").Length.Is(4);

    /// <summary>
    /// A requirement is the smallest thing that may rise, and one written above the branches runs in
    /// every one of them — so a requirement each branch repeats is stated once at the heading they
    /// share, where it was written, instead of in every block below it.
    /// </summary>
    [Fact]
    public void GivenEveryBranchRepeatsARequirement_ThenStateItOnceAbove()
        => Render(
            new("WhenAddRoom", "GivenNoSuchRoom", "ThenRespondWithJson", [Act("post"), Claim("then json")]),
            new("WhenAddRoom", "GivenNoSuchRoom", "ThenRespondCreated", [Act("post"), Claim("then created")]),
            new("WhenAddRoom", "GivenTheRoomExists", "ThenRespondWithJson", [Act("post"), Claim("then json")]),
            new("WhenAddRoom", "GivenTheRoomExists", "ThenRespondConflict", [Act("post"), Claim("then conflict")]))
            .Does()
            .Contain("## When add room\n`post`\n\n- **respond with json** — `json`\n\n### Given ")
            .and.Contain("### Given no such room\n\n- **respond created** — `created`\n")
            .and.Contain("### Given the room exists\n\n- **respond conflict** — `conflict`\n");

    /// <summary>
    /// One branch is nobody to share with: a requirement rises because the branches below repeat it,
    /// and a heading with a single branch under it has no repetition to remove.
    /// </summary>
    [Fact]
    public void GivenOneBranchOnly_ThenLeaveItsRequirementsWhereTheyAre()
        => Render(
            new("WhenAddRoom", "GivenNoSuchRoom", "ThenRespondWithJson", [Act("post"), Claim("then json")]),
            new("WhenAddRoom", "GivenNoSuchRoom", "ThenRespondCreated", [Act("post"), Claim("then created")]))
            .Does().Contain("### Given no such room\n\n- **respond with json** — `json`\n");

    /// <summary>
    /// Hoisting must never empty a block, so a branch whose every requirement is repeated elsewhere
    /// keeps one — a heading with nothing under it states less than the repetition cost.
    /// </summary>
    [Fact]
    public void GivenABranchIsNothingButRepeatedRequirements_ThenLeaveThemInPlace()
        => Render(
            new("WhenAddRoom", "GivenNoSuchRoom", "ThenRespondWithJson", [Act("post"), Claim("then json")]),
            new("WhenAddRoom", "GivenNoSuchRoom", "ThenRespondCreated", [Act("post"), Claim("then created")]),
            new("WhenAddRoom", "GivenTheRoomExists", "ThenRespondWithJson", [Act("post"), Claim("then json")]))
            .Does().Contain("## When add room\n`post`\n\n### Given ");

    /// <summary>
    /// A requirement rises no higher than the heading naming the act it is about: two subjects that
    /// happen to state the same requirement each keep it, since above them nothing names the act.
    /// </summary>
    [Fact]
    public void GivenTwoSubjectsRepeatARequirement_ThenStateItUnderEach()
        => Render(
            new("WhenAddRoom", "", "ThenRespondWithJson", [Act("post"), Claim("then json")]),
            new("WhenGetRoom", "", "ThenRespondWithJson", [Act("get"), Claim("then json")]))
            .Does()
            .Contain("## When add room\n`post`\n\n- **respond with json** — `json`\n")
            .and.Contain("## When get room\n`get`\n\n- **respond with json** — `json`\n");

    /// <summary>
    /// A lone requirement shares nothing with anyone, but its context still belongs under the
    /// heading — there is no minimum number of requirements before a heading may hold what names it.
    /// </summary>
    [Fact]
    public void GivenASingleRequirement_ThenStillStateItsOpeningAbove()
        => Render(TwoSubjects()[..1]).Does()
            .Contain("-->\n`Using api`\n")
            .and.Contain("## When get room\n`get`\n")
            .and.Contain("- **Thena** — `a`\n");

    /// <summary>
    /// The act stops at the heading named after it. Raised past that — to an area, or to the
    /// document — it would stand over requirements whose own heading says they act otherwise, and
    /// nothing at that level names it. Arrangement has no such tie and rises as far as it holds.
    /// </summary>
    [Fact]
    public void GivenEveryRequirementSharesTheAct_ThenRaiseItNoHigherThanItsSubject()
        => Render(
            Requirement("WhenGetRoom", "ThenA", Using("api"), Act("get"), Claim("then a")),
            Requirement("WhenGetRoom", "ThenB", Using("api"), Act("get"), Claim("then b")))
            .Does()
            .Contain("-->\n`Using api`\n")
            .and.Contain("## When get room\n`get`\n");

    /// <summary>Two are already repetition — the second saying it again is what makes it so.</summary>
    [Fact]
    public void GivenTwoRequirementsOpenAlike_ThenStateTheOpeningOnce()
        => Render(TwoSubjects()[..2]).Does()
            .Contain("-->\n`Using api`\n")
            .and.Contain("## When get room\n`get`\n")
            .and.Contain("- **Thena** — `a`\n");

    /// <summary>
    /// One requirement saying something else keeps that clause in every block — but only that one.
    /// What the others still agree on is decided on its own and rises anyway.
    /// </summary>
    [Fact]
    public void GivenOneRequirementSaysSomethingElse_ThenLeaveThatClauseInPlace()
    {
        var requirements = TwoSubjects()[..3];
        requirements[2] = requirements[2] with { Clauses = [Using("other"), Act("get"), Claim("then c")] };
        Render(requirements).Does()
            .Contain("## When get room\n`get`\n")
            .and.Contain("- **Thena**\n  ```\n  Using api\n  Then a\n  ```\n")
            .and.Contain("- **Thenc**\n  ```\n  Using other\n  Then c\n  ```\n");
    }

    /// <summary>Hoisting must never empty a block, so a requirement that is only the opening blocks it.</summary>
    [Fact]
    public void GivenARequirementIsNothingButTheSharedOpening_ThenLeaveTheOpeningInPlace()
    {
        var requirements = TwoSubjects()[..3];
        requirements[2] = requirements[2] with { Clauses = [Using("api")] };
        Render(requirements).Does().Contain("-->\n\n---\n\n## ");
    }

    /// <summary>
    /// A clause is stated at a heading because every requirement below says it, not because it comes
    /// first. Arrangement runs before the act, so a branch that arranges anything of its own would
    /// otherwise sit in front of the shared <c>When</c> and keep it out of the heading that names it.
    /// </summary>
    [Fact]
    public void GivenTheSharedClauseSitsBehindADifferingOne_ThenStillStateItAtTheHeading()
        => Render(
            Requirement("WhenDeleteRoom", "ThenA", Condition("load none"), Act("delete"), Claim("then a")),
            Requirement("WhenDeleteRoom", "ThenB", Condition("load one"), Act("delete"), Claim("then b")),
            Requirement("WhenAddRoom", "ThenC", Condition("load one"), Act("add"), Claim("then c")))
            .Does()
            .Contain("## When delete room\n`delete`\n")
            .and.Contain("- **a**\n  ```\n  Having load none\n  Then a\n  ```\n");

    /// <summary>The mirror: what differs may come second and what is shared first.</summary>
    [Fact]
    public void GivenTheSharedClauseComesFirst_ThenStillStateItAtTheHeading()
        => Render(
            Requirement("WhenGetRoom", "ThenA", Act("get"), Condition("post once"), Claim("then a")),
            Requirement("WhenGetRoom", "ThenB", Act("get"), Condition("post twice"), Claim("then b")),
            Requirement("WhenAddRoom", "ThenC", Act("add"), Condition("post once"), Claim("then c")))
            .Does().Contain("## When get room\n`get`\n");

    /// <summary>
    /// How often a clause is stated is part of what it states — two identical setups are two
    /// invocations — so a clause rises only as many times as every requirement says it. Hoisting it
    /// twice above a requirement that says it once would put a claim on the page nothing made.
    /// </summary>
    [Fact]
    public void GivenOneRequirementSaysAClauseFewerTimes_ThenRaiseItOnlyThatOften()
        => Render(
            Requirement("WhenGetRoom", "ThenA",
                Condition("post"), Condition("post"), Act("get"), Claim("then a")),
            Requirement("WhenGetRoom", "ThenB", Condition("post"), Act("get"), Claim("then b")))
            .Does()
            .Contain("-->\n`Having post`\n")
            .and.Contain("## When get room\n`get`\n")
            .and.Contain("- **a**\n  ```\n  Having post\n  Then a\n  ```\n")
            .and.Contain("- **b** — `b`\n");

    /// <summary>Said twice by every requirement, so it rises twice and none of it is left below.</summary>
    [Fact]
    public void GivenEveryRequirementSaysAClauseTwice_ThenRaiseItTwice()
        => Render(
            Requirement("WhenGetRoom", "ThenA", Condition("post"), Condition("post"), Claim("then a")),
            Requirement("WhenGetRoom", "ThenB", Condition("post"), Condition("post"), Claim("then b")))
            .Does()
            .Contain("-->\n```\nHaving post\n  after post\n```\n")
            .and.Contain("- **a** — `a`\n");

    /// <summary>
    /// One requirement not saying it is enough to keep it out — no partial credit. The clause every
    /// requirement does share still rises, so the two are decided one at a time.
    /// </summary>
    [Fact]
    public void GivenOneRequirementLacksTheClause_ThenLeaveThatOneInEachBlock()
        => Render(
            Requirement("WhenGetRoom", "ThenA", Condition("load"), Act("get"), Claim("then a")),
            Requirement("WhenGetRoom", "ThenB", Condition("load"), Act("get"), Claim("then b")),
            Requirement("WhenGetRoom", "ThenC", Condition("load"), Claim("then c")))
            .Does()
            .Contain("-->\n`Having load`\n")
            .and.not.Contain("## When get room\n`get`\n");

    // ----------- What the spec declares about the code, stated where it holds

    /// <summary>
    /// Both labels name the code the document describes rather than any one heading, so both rise
    /// as far as they hold. Where every spec returns the same thing, that one line at the top is
    /// the whole of what every heading below was otherwise repeating.
    /// </summary>
    [Fact]
    public void GivenEverySpecDeclaresOneReturnType_ThenRaiseItToTheDocument()
        => Render(
            Requirement("WhenGetRoom", "ThenA", Act("get"), Claim("then a"))
                with { SubjectUnderTest = "RoomService", ReturnType = "Room" },
            Requirement("WhenAddRoom", "ThenB", Act("add"), Claim("then b"))
                with { SubjectUnderTest = "RoomService", ReturnType = "Room" })
            .Does()
            .Contain("-->\n```\nSubject under test: RoomService\nReturn type: Room\n```\n")
            .and.Contain("## When get room\n`get`\n")
            .and.Contain("## When add room\n`add`\n");

    /// <summary>
    /// The types ground the requirements in the code they describe, so they are stated rather than
    /// phrased — a sentence would have to read well for every spec, and Spec&lt;int&gt; over a static
    /// calculation defeats any of them.
    /// </summary>
    [Fact]
    public void GivenEverySpecDeclaresTheSame_ThenStateItForTheDocument()
        => Render(_respondOk with { SubjectUnderTest = "HttpClient", ReturnType = "HttpResponseMessage" })
            .Does().Contain(
                "-->\n```\nSubject under test: HttpClient\nReturn type: HttpResponseMessage\n```\n");

    /// <summary>
    /// One space after each label, never a column: aligning them would make where a value starts
    /// depend on which other label happens to be stated beside it.
    /// </summary>
    [Fact]
    public void ThenLineUpTheDeclaredTypes()
        => Render(
            Requirement("WhenGetRoom", "ThenA", Claim("then a"))
                with { SubjectUnderTest = "int", ReturnType = "string" },
            Requirement("WhenAdd", "ThenB", Claim("then b"))
                with { SubjectUnderTest = "int", ReturnType = "string" })
            .Does().Contain("Subject under test: int\nReturn type: string\n");

    /// <summary>
    /// A return type is what the act yields, so where a heading states both it joins the act instead
    /// of standing as a label of its own. The subject has no clause to belong to and stays a label.
    /// </summary>
    [Fact]
    public void GivenAHeadingStatesTheReturnTypeAndTheAct_ThenSayItOnTheAct()
        => Render(
            Requirement("WhenGetRoom", "ThenA", Act("get"), Claim("then a"))
                with { SubjectUnderTest = "HttpClient", ReturnType = "HttpResponseMessage" },
            Requirement("WhenAdd", "ThenB", Act("add"), Claim("then b"))
                with { SubjectUnderTest = "int", ReturnType = "int" })
            .Does().Contain("## When add\n```\nSubject under test: int\nWhen add, returns int\n```");

    /// An act with no room left on its line for a trailing phrase.
    private const string LongAct =
        "Book(a request that is quite long, with a good many words in it to fill the line)";

    /// <summary>
    /// The type joins the act only where it costs no line. Wrapped, the phrase would start a line
    /// with the binder's comma — a statement broken where nothing relates the halves — so it
    /// becomes a label of its own, written under the act it qualifies rather than above it.
    /// </summary>
    [Fact]
    public void GivenTheReturnTypeWouldNotFitOnTheAct_ThenWriteItUnderTheAct()
        => Render(
            Requirement("WhenBook", "ThenA", Act(LongAct), Claim("then a"))
                with { SubjectUnderTest = "BookingService", ReturnType = "Booking" },
            Requirement("WhenAdd", "ThenB", Act("add"), Claim("then b"))
                with { SubjectUnderTest = "int", ReturnType = "int" })
            .Does().Contain(
                "## When book\n```\nSubject under test: BookingService\n"
                + $"When {LongAct}\nReturn type: Booking\n```");

    /// An act one column past the width — enough to break, nowhere near enough to be worth it.
    private const string SlightlyLongAct =
        "Book(new BookingRequest(a Room's RoomNumber, a string, new(2026, 8, 10), new(2026, 8, 12)))";

    /// <summary>
    /// A line a little past the width costs a reader nothing; breaking it costs a second line, an
    /// element of its own to fence it, and a seam through the middle of one expression. So the
    /// width has a tolerance, and a statement within it is written whole.
    /// </summary>
    [Fact]
    public void GivenAStatementIsOnlyALittlePastTheWidth_ThenWriteItWhole()
        => Render(
            Requirement("WhenBook", "ThenA", Act(SlightlyLongAct), Claim("then a")),
            Requirement("WhenAdd", "ThenB", Act("add"), Claim("then b")))
            .Does().Contain($"## When book\n`{SlightlyLongAct}`\n");

    /// <summary>
    /// The tolerance says whether a statement breaks, never where. Past it the statement wraps at
    /// the width — a wrapped statement is already costing its reader a seam, and paying that to
    /// end up with lines wider than the page would be paying for nothing.
    /// </summary>
    [Fact]
    public void GivenAStatementIsPastTheTolerance_ThenWrapItAtTheWidthAndNotTheTolerance()
        => Render(
            Requirement("WhenBook", "ThenA", Act(_tooLongAct), Claim("then a")),
            Requirement("WhenAdd", "ThenB", Act("add"), Claim("then b")))
            .Does().Contain($"## When book\n```\n{_head}\n    bbbbbbbb cccccccccc\n```");

    /// Words placed so that breaking at the width and breaking at the tolerance fall apart: the
    /// first word alone fills the width, the first two fit within the tolerance.
    private static readonly string _head = new('a', 85);

    private static readonly string _tooLongAct = $"{_head} {new string('b', 8)} {new string('c', 10)}";

    /// <summary>With no act at the heading it has nothing to join, so it stays a label.</summary>
    [Fact]
    public void GivenAHeadingStatesTheReturnTypeAlone_ThenKeepItALabel()
        => Render(
            Requirement("WhenGetRoom", "ThenA", Claim("then a"))
                with { SubjectUnderTest = "RoomService", ReturnType = "Room" },
            Requirement("WhenAdd", "ThenB", Claim("then b"))
                with { SubjectUnderTest = "RoomService", ReturnType = "int" })
            .Does().Contain("## When get room\n`Return type: Room`\n");

    [Fact]
    public void GivenSpecsDeclareDifferently_ThenStateItForEachSubject()
        => Render(
            Requirement("WhenGetRoom", "ThenA", Act("get"), Claim("then a"))
                with { SubjectUnderTest = "HttpClient", ReturnType = "HttpResponseMessage" },
            Requirement("WhenAdd", "ThenB", Act("add"), Claim("then b"))
                with { SubjectUnderTest = "int", ReturnType = "int" })
            .Does()
            .Contain("## When get room\n```\nSubject under test: HttpClient\n")
            .and.Contain("## When add\n```\nSubject under test: int\n");

    /// <summary>Stated where it holds and not again below, since saying it once is the point.</summary>
    [Fact]
    public void GivenTheDocumentStatesTheTypes_ThenDoNotRepeatThemPerSubject()
        => Render([.. TwoSubjects().Select(entry => entry with
                { SubjectUnderTest = "HttpClient", ReturnType = "HttpResponseMessage" })])
            .Split("Subject under test").Length.Is(2);

    [Fact]
    public void GivenTheSpecDeclaresNothing_ThenSayNothingAboutTypes()
        => Render(_respondOk).Does().not.Contain("Subject under test");

    /// One subject throughout, each section returning something of its own.
    private static SpecificationEntry[] OneSubjectManyReturnTypes()
        => [Requirement("WhenGetRoom", "ThenA", Act("get"), Claim("then a"))
                with { SubjectUnderTest = "RoomService", ReturnType = "Room" },
            Requirement("WhenListRooms", "ThenB", Act("list"), Claim("then b"))
                with { SubjectUnderTest = "RoomService", ReturnType = "Room[]" }];

    /// <summary>
    /// The two labels are hoisted one at a time. Held together, a single disagreeing return type
    /// would drag the subject down with it and have every section restate a name that never changes.
    /// </summary>
    [Fact]
    public void GivenOneSubjectDeclaresSeveralReturnTypes_ThenStillStateTheSubjectForTheDocument()
        => Render(OneSubjectManyReturnTypes()).Does()
            .Contain("-->\n`Subject under test: RoomService`\n")
            .and.Contain("## When get room\n`get, returns Room`\n")
            .and.Contain("## When list rooms\n`list, returns Room[]`\n");

    /// <summary>Hoisted is stated once: the subject does not come back under each section.</summary>
    [Fact]
    public void GivenTheDocumentStatesTheSubject_ThenDoNotRepeatItPerSubject()
        => Render(OneSubjectManyReturnTypes()).Split("Subject under test").Length.Is(2);

    /// <summary>
    /// The two labels are hoisted one at a time in both directions: a return type they agree on
    /// rises past the subjects they differ in, which stay at the headings that name them.
    /// </summary>
    [Fact]
    public void GivenSeveralSubjectsDeclareOneReturnType_ThenRaiseItPastTheSubjectsAnyway()
        => Render(
            Requirement("WhenGetRoom", "ThenA", Act("get"), Claim("then a"))
                with { SubjectUnderTest = "RoomService", ReturnType = "Room" },
            Requirement("WhenAdd", "ThenB", Act("add"), Claim("then b"))
                with { SubjectUnderTest = "RoomStore", ReturnType = "Room" })
            .Does()
            .Contain("-->\n`Return type: Room`\n")
            .and.Contain("## When get room\n```\nSubject under test: RoomService\nWhen get\n```")
            .and.Contain("## When add\n```\nSubject under test: RoomStore\nWhen add\n```");

    /// <summary>
    /// A return type follows the act because it qualifies it. With no act at the heading there is
    /// nothing for it to follow, so it stands beside the subject rather than under whatever
    /// arrangement happens to be stated in the same block.
    /// </summary>
    [Fact]
    public void GivenAHeadingStatesTheTypesAndArrangement_ThenKeepTheLabelsTogether()
        => Render(
            Requirement("WhenNext", "ThenA", Using("the seed"), Claim("then a"))
                with { SubjectUnderTest = "BookingNumberGenerator", ReturnType = "int" },
            Requirement("WhenNext", "ThenB", Using("the seed"), Claim("then b"))
                with { SubjectUnderTest = "BookingNumberGenerator", ReturnType = "int" })
            .Does().Contain(
                "Subject under test: BookingNumberGenerator\nReturn type: int\nUsing the seed\n");

    [Fact]
    public void GivenAHeadingStatesOneLabelAlone_ThenStillWriteItWithOneSpace()
        => Render(OneSubjectManyReturnTypes()).Does().not.Contain("Return type:  ");

    // ----------- Sections are ordered by how much arrangement they carry, simplest first

    /// <summary>
    /// The document's sections in the order they appear: each heading as it reads, and each
    /// requirement by the label that names it, which is all an ordering rule can be seen in.
    /// </summary>
    private static string[] Outline(string document)
        => [.. document.Split('\n')
            .Where(line => line.StartsWith("##", StringComparison.Ordinal) || IsItem(line))
            .Select(line => IsItem(line) ? Label(line) : line)];

    private static bool IsItem(string line) => line.StartsWith("- **", StringComparison.Ordinal);

    /// An item's label, without the claim standing beside it.
    private static string Label(string item)
        => item[..(item.IndexOf("**", 4, StringComparison.Ordinal) + 2)];

    private static string[] SubjectHeadings(string document)
        => [.. document.Split('\n').Where(line => line.StartsWith("## ", StringComparison.Ordinal))];

    /// <summary>
    /// The alphabetically first subject is the one that arranges more, and it comes last — so the
    /// order is the rule's and not the alphabet's.
    /// </summary>
    [Fact]
    public void GivenOneSubjectArrangesMore_ThenPlaceTheSimplerFirst()
        => Outline(Render(
            new("WhenAddRoom", "GivenNoSuchRoom", "ThenA", [Act("post"), Claim("then a")]),
            new("WhenAddRoom", "GivenTheRoomExists", "ThenB", [Act("post"), Condition("post"), Claim("then b")]),
            new("WhenGetVersion", "", "ThenC", [Act("get"), Claim("then c")])))
            .Is().EqualTo([
                "## When get version",
                "- **c**",
                "## When add room",
                "### Given no such room",
                "- **a**",
                "### Given the room exists",
                "- **b**"]);

    [Fact]
    public void GivenOneBranchArrangesMore_ThenPlaceTheSimplerFirst()
        => Outline(Render(
            new("WhenGetRoom", "GivenAaa", "ThenA", [Act("get"), Condition("post"), Claim("then a")]),
            new("WhenGetRoom", "GivenZzz", "ThenB", [Act("get"), Claim("then b")])))
            .Is().EqualTo([
                "## When get room",
                "### Given zzz",
                "- **b**",
                "### Given aaa",
                "- **a**"]);

    [Fact]
    public void GivenOneRequirementArrangesMore_ThenPlaceTheSimplerFirst()
        => Outline(Render(
            new("WhenGetRoom", "GivenX", "ThenA", [Act("get"), Condition("post"), Claim("then a")]),
            new("WhenGetRoom", "GivenX", "ThenB", [Act("get"), Claim("then b")])))
            .Is().EqualTo(["## When get room", "### Given x", "- **b**", "- **a**"]);

    /// <summary>
    /// Requirements that arrange alike are ordered by how much they claim, so a short status check
    /// precedes one that inspects a whole value. Length only ever breaks a tie — it never overrides
    /// arrangement, and it decides nothing above the leaf.
    /// </summary>
    [Fact]
    public void GivenTwoRequirementsArrangeAlike_ThenPlaceTheShorterClaimFirst()
        => Outline(Render(
            new("WhenGetRoom", "GivenX", "ThenA", [Act("get"), Claim("then the whole room is returned")]),
            new("WhenGetRoom", "GivenX", "ThenB", [Act("get"), Claim("then ok")])))
            .Is().EqualTo(["## When get room", "### Given x", "- **b**", "- **a**"]);

    /// <summary>
    /// Assertions are not counted, and this is why: a suite grows by claiming more, and a document
    /// that reshuffled every time it did would spend the diff it is reviewed for.
    /// </summary>
    [Fact]
    public void GivenARequirementIsAdded_ThenLeaveTheOrderOfSubjectsAlone()
    {
        SpecificationEntry[] before = [
            new("WhenAaa", "", "ThenA", [Act("aaa"), Condition("post"), Claim("then a")]),
            new("WhenZzz", "", "ThenB", [Act("zzz"), Claim("then b")])];
        SubjectHeadings(Render(before)).Is().EqualTo(["## When zzz", "## When aaa"]);
        SubjectHeadings(Render([.. before, new("WhenZzz", "", "ThenC", [Act("zzz"), Claim("then c")])]))
            .Is().EqualTo(["## When zzz", "## When aaa"]);
    }

    // ----------- What the namespaces differ in is the outermost level of structure

    /// A requirement of a subject in a namespace, arranging nothing of its own.
    private static SpecificationEntry InNamespace(string @namespace, string subject, string name)
        => new(subject, "", name, [Claim(name.AsWords())], Namespace: @namespace);

    /// The document's outermost headings, the title excepted — it is one of them by level only.
    private static string[] AreaHeadings(string document)
        => [.. document.Split('\n').Skip(1).Where(line => line.StartsWith("# ", StringComparison.Ordinal))];

    /// <summary>
    /// A spec project lays its classes out in folders, and the namespace is what reaches the run —
    /// so the segment they differ in heads the sections it names, above the subjects it holds.
    /// </summary>
    [Fact]
    public void GivenTheNamespacesDiffer_ThenHeadEachSectionWithWhatItDiffersIn()
        => Render(
            InNamespace("MyHotel.Spec.Rooms", "WhenAddRoom", "ThenA"),
            InNamespace("MyHotel.Spec.Bookings", "WhenBookRoom", "ThenB"))
            .Does()
            .Contain("\n# Bookings\n\n## When book room\n")
            .and.Contain("\n# Rooms\n\n## When add room\n");

    /// <summary>
    /// A heading over the whole document names nothing that tells anything in it from anything else,
    /// so a project whose specs share one namespace reads exactly as it did before there was a level.
    /// </summary>
    [Fact]
    public void GivenEveryNamespaceIsTheSame_ThenWriteNoHeadingForIt()
        => AreaHeadings(Render(
            InNamespace("MyHotel.Spec.Rooms", "WhenAddRoom", "ThenA"),
            InNamespace("MyHotel.Spec.Rooms", "WhenGetRoom", "ThenB")))
            .Is().Empty();

    /// <summary>
    /// A spec at the root belongs to no section, and the title is the heading it already has — so it
    /// is written under the title, before the first heading that would otherwise swallow it.
    /// </summary>
    [Fact]
    public void GivenASpecSitsAtTheSharedRoot_ThenWriteItAboveTheFirstHeading()
        => Render(
            InNamespace("MyHotel.Spec", "WhenGetVersion", "ThenA"),
            InNamespace("MyHotel.Spec.Rooms", "WhenAddRoom", "ThenB"))
            .Does().Contain(
                "---\n\n## When get version\n\n- **a** — `a`\n\n# Rooms\n\n## When add room\n");

    /// <summary>
    /// One class under test per area leaves the area's own heading saying everything there is to
    /// say, so what runs below it is not written: a heading per area and one below it naming the
    /// only thing in it would be the same division twice.
    /// </summary>
    [Fact]
    public void GivenTheNamespacesRunDeeper_ThenHeadOnlyTheSegmentTheyDifferIn()
        => Render(
            InNamespace("MyHotel.Core.Spec.Rooms.RoomService", "WhenAddRoom", "ThenA"),
            InNamespace("MyHotel.Core.Spec.Bookings.BookingService", "WhenBook", "ThenB"))
            .Does().Contain("\n# Bookings\n").and.Contain("\n# Rooms\n").and.not.Contain("Service");

    /// <summary>
    /// A test that asserts nothing never runs its pipeline, so it states nothing at all. Listed by
    /// name alone it reads as a requirement somebody verified, which is the one thing the document
    /// must not say — so the claim slot says what is missing instead.
    /// </summary>
    [Fact]
    public void GivenARequirementClaimsNothing_ThenSayItIsStillToDo()
        => Render(Requirement("WhenGetRoom", "ThenAuthorizeRequest"))
            .Does().Contain("- **authorize request** — *TODO: Assert behaviour*\n");

    // ----------- A nested branch heads twice, where there is depth left to spend

    private static SpecificationEntry OfBranchPath(string branch, string name, params SpecificationClause[] own)
        => new("WhenGetRoom", branch, name, [Act("get"), .. own]);

    /// <summary>
    /// Four heading levels is the limit of what reads, so a nested branch heads twice only where the
    /// first one lands at three. What it buys is the hoist: the outer heading can state what every
    /// branch below it says, which one flattened heading has no level to hold.
    /// </summary>
    [Fact]
    public void GivenANestedBranch_ThenHeadEachLevelSeparately()
        => Render(
            OfBranchPath("GivenTheRoomExists.WithItems", "ThenA", Claim("then a")),
            OfBranchPath("GivenTheRoomExists.WithNoItems", "ThenB", Claim("then b")))
            .Does()
            .Contain("\n### Given the room exists\n")
            .and.Contain("\n#### With items\n")
            .and.Contain("\n#### With no items\n")
            .and.not.Contain("Given the room exists, with");

    [Fact]
    public void GivenANestedBranchSharesAClause_ThenStateItAtTheOuterHeading()
        => Render(
            OfBranchPath("GivenTheRoomExists.WithItems", "ThenA", Condition("post"), Claim("then a")),
            OfBranchPath("GivenTheRoomExists.WithNoItems", "ThenB", Condition("post"), Claim("then b")),
            OfBranchPath("GivenNoSuchRoom", "ThenC", Claim("then c")))
            .Does()
            .Contain("\n### Given the room exists\n`Having post`\n")
            .and.Contain("\n#### With items\n\n- **a** — `a`\n");

    /// <summary>A branch that never nested keeps the one heading it had.</summary>
    [Fact]
    public void GivenAFlatBranch_ThenHeadItOnce()
        => Render(OfBranchPath("GivenTheRoomExists", "ThenA", Claim("then a")))
            .Does().Contain("\n### Given the room exists\n").and.not.Contain("####");

    /// <summary>
    /// A group heading has already spent the level a nested branch would take, so there the path
    /// stays one heading — four levels being the limit, and the group having claimed the third.
    /// </summary>
    [Fact]
    public void GivenAGroupHeadingSpentTheLevel_ThenFlattenTheBranchPath()
        => Render(
            new("WhenX", "GivenOne.AndTwo", "ThenA", [Act("get"), Claim("then a")], Namespace: "A.B.C"),
            new("WhenX", "GivenOne.AndThree", "ThenB", [Act("get"), Claim("then b")], Namespace: "A.B.D"),
            InNamespace("E.F", "WhenY", "ThenC"))
            .Does()
            .Contain("\n#### Given one, and two\n")
            .and.Contain("\n#### Given one, and three\n")
            .and.not.Contain("#####");

    /// <summary>
    /// Where an area holds more than one namespace below it, each heads a group of its own: the
    /// area names what they share and the group what tells them apart. Everything left below the
    /// area merges into one name, the dots separating parts of it rather than sentences.
    /// </summary>
    [Fact]
    public void GivenAnAreaHoldsSeveralNamespaces_ThenGroupThemBelowIt()
        => Render(
            InNamespace("A.B.C", "WhenX", "ThenA"),
            InNamespace("A.B.D", "WhenX", "ThenB"),
            InNamespace("E.F.G", "WhenX", "ThenC"),
            InNamespace("E.H.I", "WhenX", "ThenD"))
            .Does()
            .Contain("\n# A\n\n## B C\n").and.Contain("\n## B D\n")
            .and.Contain("\n# E\n\n## F G\n").and.Contain("\n## H I\n");

    /// <summary>
    /// A group heading pushes what is under it a level down, so a subject sits below the group that
    /// holds it — and stays where it was in an area that never grouped, rather than paying a level
    /// for a division that was not made.
    /// </summary>
    [Fact]
    public void GivenOnlyOneAreaGroups_ThenLeaveTheOtherAtItsOwnDepth()
        => Render(
            InNamespace("A.Rooms.RoomService", "WhenAddRoom", "ThenA"),
            InNamespace("A.Bookings.BookingService", "WhenBook", "ThenB"),
            InNamespace("A.Bookings.BookingNumberGenerator", "WhenNext", "ThenC"))
            .Does()
            .Contain("\n# Rooms\n\n## When add room\n")
            .and.Contain("\n# Bookings\n\n## Booking Number Generator\n\n### When next\n");

    /// <summary>
    /// The level hoists like every other: what everything under a heading declares is stated at it.
    /// This is the level that earns it — one folder per class under test names one subject each.
    /// </summary>
    [Fact]
    public void GivenEverySpecOfAnAreaDeclaresTheSame_ThenStateItAtItsHeading()
        => Render(
            InNamespace("MyHotel.Core.Spec.Rooms", "WhenAddRoom", "ThenA")
                with { SubjectUnderTest = "RoomService" },
            InNamespace("MyHotel.Core.Spec.Rooms", "WhenGetRoom", "ThenB")
                with { SubjectUnderTest = "RoomService" },
            InNamespace("MyHotel.Core.Spec.Bookings", "WhenBook", "ThenC")
                with { SubjectUnderTest = "BookingService" })
            .Does()
            .Contain("# Bookings\n`Subject under test: BookingService`\n")
            .and.Contain("# Rooms\n`Subject under test: RoomService`\n");

    /// <summary>A clause every requirement of an area states settles at the area's heading.</summary>
    [Fact]
    public void GivenEveryRequirementOfAnAreaOpensAlike_ThenStateThatOnceForTheArea()
        => Render(
            InNamespace("A.Rooms", "WhenAddRoom", "ThenA") with { Clauses = [Condition("post"), Claim("then a")] },
            InNamespace("A.Rooms", "WhenGetRoom", "ThenB") with { Clauses = [Condition("post"), Claim("then b")] },
            InNamespace("A.Bookings", "WhenBook", "ThenC"))
            .Does().Contain("# Rooms\n`Having post`\n").and.Contain("- **a** — `a`\n");

    /// <summary>Areas are ordered by the rule the levels below them use: simplest first.</summary>
    [Fact]
    public void GivenOneAreaArrangesMore_ThenPlaceTheSimplerFirst()
        => AreaHeadings(Render(
            InNamespace("A.Aaa", "WhenA", "ThenA") with { Clauses = [Condition("post"), Claim("then a")] },
            InNamespace("A.Zzz", "WhenB", "ThenB")))
            .Is().EqualTo(["# Zzz", "# Aaa"]);

    /// <summary>Two classes of one name in different areas are two requirements, not a duplicate.</summary>
    [Fact]
    public void GivenTwoAreasHoldASubjectOfTheSameName_ThenRenderBoth()
        => AreaHeadings(Render(
            InNamespace("A.Rooms", "WhenGet", "ThenA"),
            InNamespace("A.Bookings", "WhenGet", "ThenA")))
            .Is().EqualTo(["# Bookings", "# Rooms"]);
}
